/// C2/I1 — 카드 라이브러리 + 리졸버.
///
/// 범위: 초급 CARD-01~18 + 음색 TONE-01~13 + Universal Core UC-01~25 +
/// Repertoire Application RA-01~10 + 장르별 IM/CL/GY/RB/RK/WC 카드.
/// 초급 소스: docs/curriculum/beginner/cards.md.
/// 중급/고급 소스: docs/curriculum/universal-core, advanced-* 문서.
/// 고위험 고급 카드는 safetyReview=pending + safety_signoff.dart +
/// SAFETY-RELEASE-GATE.md 조건 충족 전 기본 잠금.
library;

import 'card.dart';
import '../progression/path.dart';
import '../safety/safety_signoff.dart';

const Map<String, Card> kCardLibrary = {
  'CARD-01': Card(
    id: 'CARD-01',
    cue: [
      '바닥/의자에 편하게.',
      '턱·어깨 힘 빼기.',
      '6점 균형 의식만 — 움직이지 않기.',
    ],
    voicedMicroWin: ['끝에 편한 /m/ 3회(각 2–3초)'],
    anatomyEntry: '가벼운 신체 스캔',
    anatomyMain: '6점 정렬 관찰',
    anatomyCooldown: '느린 호흡 3회',
    variableAxes: {
      'sessionPos': ['워밍업', '본'],
    },
  ),
  'CARD-02': Card(
    id: 'CARD-02',
    cue: [
      '코로 천천히 들이쉬고 늑골·배가 같이 부풀게.',
      '배만으로 ❌, 늑골도.',
      '내쉴 때 어깨 ❌.',
    ],
    voicedMicroWin: ['voiced 한숨 /h→a/ 3회(음정 안 정함)'],
    anatomyEntry: '무음 호흡 관찰',
    anatomyMain: '늑골-복부 결합 호흡',
    anatomyCooldown: '느린 날숨 연장',
    variableAxes: {
      'sessionPos': ['워밍업', '본'],
    },
  ),
  'CARD-03': Card(
    id: 'CARD-03',
    cue: [
      '턱을 무겁게 떨어뜨리기.',
      '혀 뿌리 내려놓기.',
      'silent ah 후 가벼운 voiced ah.',
    ],
    voicedMicroWin: ['가벼운 /a/ 3회(편한 중음)'],
    anatomyEntry: '턱·혀 풀기',
    anatomyMain: 'silent ah → voiced ah',
    anatomyCooldown: '하품-한숨 1회',
    variableAxes: {
      'sessionPos': ['워밍업', '본'],
    },
  ),
  'CARD-04': Card(
    id: 'CARD-04',
    cue: [
      '치지 말고 숨을 흘려보내듯 /h/.',
      '/h/에 가볍게 소리 얹기 → /m/.',
      '크게 ❌, 편하게.',
    ],
    voicedMicroWin: ['/h/-led 부드러운 onset 5회'],
    anatomyEntry: '무성 호기 3회',
    anatomyMain: '/h/→/m/ easy onset',
    anatomyCooldown: '가벼운 /m/ 하행',
    variableAxes: {
      'range': ['편한 중음', '약간 낮게'],
      'sessionPos': ['워밍업', '본'],
    },
  ),
  'CARD-05': Card(
    id: 'CARD-05',
    cue: [
      '짧게 소리 내고 멈춰 듣기.',
      '내 느낌 말고 화면 곡선을 보기.',
      '(블록4) 균형/과기식/과압착 중 어디로 보이는지 표시.',
    ],
    voicedMicroWin: ['편한 음 2–3초 발성 후 시각 곡선 확인 3회'],
    anatomyEntry: '짧은 발성',
    anatomyMain: '발성→시각 곡선 대조',
    anatomyCooldown: '가벼운 허밍',
    variableAxes: {
      'range': ['중음', '약간 높/낮'],
      'vowel': ['a', 'i', 'u'],
    },
  ),
  'CARD-06': Card(
    id: 'CARD-06',
    cue: [
      '5–6mm 빨대를 입술 안에 부드럽게.',
      '이로 물지 마세요.',
      '빨대로 /u/ 5초, 편한 중음.',
      '어지러우면 즉시 멈추세요.',
    ],
    voicedMicroWin: ['빨대 /u/ sustain 5초 × 3'],
    anatomyEntry: '무음 빨대 호기 1회',
    anatomyMain: '빨대 /u/ sustain 반복',
    anatomyCooldown: '빨대 빼고 /u/ 1회',
    variableAxes: {
      'range': ['중음', '±2도'],
      'vowel': ['u', 'a'],
    },
  ),
  'CARD-07': Card(
    id: 'CARD-07',
    cue: [
      '입술 힘 빼고 부르르 떨기.',
      '일정하게 유지.',
      '편한 음으로 5초.',
    ],
    voicedMicroWin: ['립 트릴 sustain 5초 × 3, 가벼운 글라이드 1회'],
    anatomyEntry: '무성 입술 트릴',
    anatomyMain: '유성 트릴 sustain·글라이드',
    anatomyCooldown: '가벼운 허밍',
    variableAxes: {
      'range': ['중음', '±2도'],
      'glide': ['sustain', '작은 5도 글라이드'],
    },
  ),
  'CARD-08': Card(
    id: 'CARD-08',
    cue: [
      '입 다물고 /m/ 콧대 진동 느끼기.',
      '짜내지 말기.',
      '/ŋ/로 바꿔 같은 느낌.',
    ],
    voicedMicroWin: ['/m/ 5초 × 2, /ŋ/ 5초 × 2'],
    anatomyEntry: '가벼운 /m/',
    anatomyMain: '/m/·/ŋ/ sustain·작은 글라이드',
    anatomyCooldown: '하행 허밍',
    variableAxes: {
      'range': ['중음', '±3도'],
      'vowel': ['m', 'ŋ'],
      'glide': ['sustain', '글라이드'],
    },
  ),
  'CARD-09': Card(
    id: 'CARD-09',
    cue: [
      '컵 물에 빨대 1–2cm 담그기.',
      '버블 일정하게.',
      '약한 강도로 5초.',
    ],
    voicedMicroWin: ['물 버블 발성 5초 × 3'],
    anatomyEntry: '무음 버블 1회',
    anatomyMain: '유성 물 버블 반복',
    anatomyCooldown: '빨대 빼고 /u/ 1회',
    variableAxes: {
      'range': ['중음'],
      'glide': ['sustain'],
    },
  ),
  'CARD-10': Card(
    id: 'CARD-10',
    cue: [
      '숨 너무 새지도(과기식) 꽉 막지도(과압착) 않게.',
      '그 사이 편한 지점에서 5초.',
      '짜내지 말기.',
    ],
    voicedMicroWin: ['편한 음 sustain 5초 × 4'],
    anatomyEntry: '가벼운 onset',
    anatomyMain: '균형 지점 탐색 sustain',
    anatomyCooldown: '가벼운 허밍',
    variableAxes: {
      'range': ['중음', '±3도'],
      'vowel': ['a', 'i', 'u'],
    },
  ),
  'CARD-11': Card(
    id: 'CARD-11',
    cue: [
      '편한 음 2초 녹음.',
      '재생을 듣기.',
      '방금 그 소리를 다시 따라하기.',
      '5회 반복.',
    ],
    voicedMicroWin: ['자기 녹음 모방 발성 5회'],
    anatomyEntry: '편한 음 1회',
    anatomyMain: '녹음→재생→재모방→시각 비교 5회',
    anatomyCooldown: '가벼운 /m/',
    variableAxes: {
      'range': ['중음', '±3도'],
      'vowel': ['a', 'u'],
    },
  ),
  'CARD-12': Card(
    id: 'CARD-12',
    cue: [
      '기준 허밍을 먼저 2초.',
      '끝난 뒤 곡선 보기.',
      '목표선은 오늘의 편한 높이.',
      '빗나가도 작게 다시.',
    ],
    voicedMicroWin: ['기준 허밍 + 목표선 매칭 5회(각 3–5초)'],
    anatomyEntry: '가벼운 글라이드',
    anatomyMain: '기준 F0→상대 목표선→확인형 피드백',
    anatomyCooldown: '하행 글라이드 1회',
    variableAxes: {
      'range': ['중음', '±3도', '약간 확장'],
      'vowel': ['a', 'i', 'u'],
      'glide': ['고정음', '작은 글라이드'],
    },
    relativePitchTarget: true,
    toleranceIntervalSemitones: 3, // ±3도 매칭 — 좁은 간격
    deferredVisualFeedback: true,
  ),
  'CARD-13': Card(
    id: 'CARD-13',
    cue: [
      '조용한 곳에서.',
      '/a/ /i/ /u/ 각 3초.',
      '표준 문장 1줄 읽기.',
      '/a/로 작은 저→고→저 글라이드.',
      '듣고 tone tag 하나 선택.',
    ],
    voicedMicroWin: ['짧은 모음 3종 + 작은 글라이드 기준 녹음'],
    anatomyEntry: '환경 확인',
    anatomyMain: '고정 과제 녹음 — 내 기준 목소리 담기',
    anatomyCooldown: '가벼운 허밍',
    timbreTags: ['bright', 'warm', 'clear', 'soft', 'comfortable', 'tired'],
    timbreLayer: 'learningSafety',
    toneTagOptions: [
      'clean', 'bright', 'warm', 'clear', 'soft', 'round',
      'comfortable', 'tired',
    ],
    allowsToneAB: true,
    requiresSameRecordingCondition: true,
    acousticFeedbackLevel: 'ab',
    maxTakeCount: 1,
    maxDurationSec: 60,
    maxSustainSec: 3,
  ),
  'CARD-14': Card(
    id: 'CARD-14',
    cue: [
      '기준음을 듣기.',
      '2초 조용히 떠올리기.',
      '입 다물고 /m/으로 따라가기.',
      '끝난 뒤 곡선 보기.',
    ],
    voicedMicroWin: ['듣기→상상→허밍 5회'],
    anatomyEntry: '기준음 듣기',
    anatomyMain: '청음→내적 상상→허밍 전이',
    anatomyCooldown: '가벼운 /m/ 하행',
    variableAxes: {
      'range': ['편한 중음', '약간 낮게'],
      'vowel': ['m', 'u'],
    },
    deferredVisualFeedback: true,
  ),
  'CARD-15': Card(
    id: 'CARD-15',
    cue: [
      '화면 4박을 보기.',
      '손가락으로 먼저 탭.',
      '/m/으로 음-음-쉼-음.',
      '빨라지면 작게 쉬기.',
    ],
    voicedMicroWin: ['4박 pulse에 맞춘 리듬 허밍 5회'],
    anatomyEntry: '4박 pulse 보기',
    anatomyMain: 'tap→/m/ 리듬 허밍',
    anatomyCooldown: '느린 호흡 3회',
    variableAxes: {
      'tempo': ['느림', '조금 느림'],
      'pattern': ['음-음-쉼-음', '음-쉼-음-음'],
    },
  ),
  'CARD-16': Card(
    id: 'CARD-16',
    cue: [
      '세 음 모양 듣기.',
      '낮음→높음→낮음 모양만 따라가기.',
      '/m/ 또는 /u/로 작게.',
      '음 이름은 보지 않기.',
    ],
    voicedMicroWin: ['2–3음 contour 허밍 5회'],
    anatomyEntry: '세 음 모양 듣기',
    anatomyMain: '짧은 선율 모양 허밍',
    anatomyCooldown: '가벼운 하행 허밍',
    variableAxes: {
      'contour': ['저-고-저', '같-고-같', '고-저-같'],
      'vowel': ['m', 'u'],
    },
    deferredVisualFeedback: true,
  ),
  'CARD-17': Card(
    id: 'CARD-17',
    cue: [
      '/마-미-무/ 천천히.',
      '자음은 부드럽게.',
      '모음은 크게 벌리지 않기.',
      '같은 높이 느낌 유지.',
    ],
    voicedMicroWin: ['한국어 3음절 bridge 5회'],
    anatomyEntry: '가벼운 /m/ 준비',
    anatomyMain: '한국어 모음·자음 저부하 전이',
    anatomyCooldown: '입 다문 허밍 1회',
    variableAxes: {
      'syllable': ['마-미-무', '나-네-노', '음-아', '무-아'],
      'range': ['편한 중음', '약간 낮게'],
    },
  ),
  'CARD-18': Card(
    id: 'CARD-18',
    cue: [
      '오늘 목 상태를 하나 고르기.',
      '정상 진도 카드가 아닌 회복 대체 루틴.',
      '피곤하면 낮은 부하만.',
      '쉰 느낌이면 듣기·호흡만.',
    ],
    voicedMicroWin: ['목이 편하면 가벼운 /m/ 2회, 아니면 무성 호흡 3회'],
    anatomyEntry: '목 상태 1탭 선택',
    anatomyMain: '상태별 동적 recovery fallback',
    anatomyCooldown: '느린 호흡 3회',
    variableAxes: {
      'mode': ['낮은 부하', 'SOVT-only', '듣기·호흡'],
    },
    safetyIntensity: 'low',
  ),

  // ===== R5 초급 확장 카드(CARD-19~34) — 리서치 6블록 충실화 =====
  // 블록1 셋업·안전
  'CARD-19': Card(
    id: 'CARD-19',
    cue: [
      '통증·피곤함·노력감을 하나씩 떠올리기.',
      '어제보다 무겁거나 쉰 느낌이면 낮은 부하 선택.',
      '통증·갑작스런 음역 손실이면 듣기·호흡만.',
      '애매하면 더 안전한 쪽으로.',
    ],
    voicedMicroWin: ['오늘 목 상태를 한 번 정직하게 확인'],
    anatomyEntry: '상태 1탭 선택',
    anatomyMain: '오늘 부하 게이트',
    anatomyCooldown: '느린 호흡 3회',
    maxDurationSec: 120,
    safetyIntensity: 'low',
  ),
  'CARD-20': Card(
    id: 'CARD-20',
    cue: [
      '코로 조용히, 이 구절에 필요한 만큼만 들이쉬기.',
      '입으로 4초 고르게 흘려보내기, 소리 ❌.',
      '입 앞 휴지가 흔들리지 않게.',
      '어깨·목은 가만히.',
    ],
    voicedMicroWin: ['흔들림 없는 조용한 날숨 4초 × 3'],
    anatomyEntry: '무음 호흡 관찰',
    anatomyMain: '무성 호기 안정화',
    anatomyCooldown: '느린 날숨 연장',
    maxSustainSec: 4,
    variableAxes: {
      'sessionPos': ['워밍업', '본'],
    },
  ),
  'CARD-21': Card(
    id: 'CARD-21',
    cue: [
      '한숨 쉬듯 "음~"으로 가장 편한 높이 찾기.',
      '너무 높거나 낮으면 즉시 내리기, 밀지 ❌.',
      '그 음을 3초 유지하며 흔들림 줄이기.',
      '이 음을 내 기준 음으로.',
    ],
    voicedMicroWin: ['내게 편한 기준 음 3초 × 3'],
    anatomyEntry: '가벼운 한숨',
    anatomyMain: '편안한 기준 음 찾기',
    anatomyCooldown: '하행 허밍 1회',
    maxSustainSec: 3,
    variableAxes: {
      'vowel': ['m', 'u'],
    },
  ),
  // 블록2 SOVT 기초
  'CARD-22': Card(
    id: 'CARD-22',
    cue: [
      '앞니에 아랫입술 가볍게 대고 "브이—" 약하게 3초.',
      '마찰을 세게 밀지 말고 가늘게.',
      '소리 켜진 그대로 /a/로 미끄러지기(브-아).',
      '목이 조이면 더 낮게.',
    ],
    voicedMicroWin: ['공기 새지 않는 /v/→모음 전이 5회'],
    anatomyEntry: '가벼운 /v/',
    anatomyMain: '유성 마찰음 → 모음 브릿지',
    anatomyCooldown: '가벼운 /m/',
    maxSustainSec: 5,
    variableAxes: {
      'vowel': ['a', 'o'],
    },
  ),
  'CARD-23': Card(
    id: 'CARD-23',
    cue: [
      '입 다물고 "응—"(/ŋ/) 5초, 혀 뒤 닿는 느낌.',
      '작게 위아래 글라이드 1회.',
      '"응-아"로 모음 열기.',
      '혀뿌리·턱 힘 들어가면 풀고 다시.',
    ],
    voicedMicroWin: ['NG→모음 전이 5회'],
    anatomyEntry: '가벼운 /ŋ/',
    anatomyMain: 'NG에서 모음 열기',
    anatomyCooldown: '하행 허밍',
    maxSustainSec: 5,
    variableAxes: {
      'vowel': ['아', '오', '우'],
    },
  ),
  // 블록3 이지 온셋·단일음
  'CARD-24': Card(
    id: 'CARD-24',
    cue: [
      '/a/를 작고 짧게, 공기 먼저도 딱 소리도 없이.',
      '아주 작은 silent-h를 상상만(과한 /h/ ❌).',
      '/e/, /o/도 같은 방식.',
      '터지거나 눌리면 /m/ 허밍으로 리셋.',
    ],
    voicedMicroWin: ['모음 단독 균형 시작 5회'],
    anatomyEntry: '가벼운 /m/ 준비',
    anatomyMain: '모음 단독 균형 온셋',
    anatomyCooldown: '가벼운 허밍',
    maxSustainSec: 5,
    variableAxes: {
      'vowel': ['a', 'e', 'o'],
    },
  ),
  'CARD-25': Card(
    id: 'CARD-25',
    cue: [
      '사람 목소리 단일음 듣기.',
      '1–2초 짧게 떠올린 뒤 "두~"로 따라가기.',
      '같은 음 6–10회, 중심에 가까이.',
      '밀어 올리지 말고 바로 안착.',
    ],
    voicedMicroWin: ['사람 음색 단일음 모방 6–10회'],
    anatomyEntry: '기준음 듣기',
    anatomyMain: '사람 목소리 단일음 매칭',
    anatomyCooldown: '가벼운 /m/ 하행',
    maxSustainSec: 2,
    deferredVisualFeedback: true,
    variableAxes: {
      'vowel': ['두', '우'],
    },
  ),
  'CARD-26': Card(
    id: 'CARD-26',
    cue: [
      '기준 음에서 살짝 위 음 모방.',
      '기준 음에서 살짝 아래 음 모방.',
      '가장 잘 맞고 편한 구간 고르기.',
      '그 키를 단일음 연습 기본 키로.',
    ],
    voicedMicroWin: ['내 최적 키 구간 찾기'],
    anatomyEntry: '기준 음 1회',
    anatomyMain: '최적 키 단일음 스윕',
    anatomyCooldown: '하행 허밍',
    maxSustainSec: 2,
    deferredVisualFeedback: true,
    relativePitchTarget: true,
    toleranceIntervalSemitones: 3, // 살짝 위/아래 음 모방 — 좁은 간격
  ),
  // 블록4 컨투어·리듬
  'CARD-27': Card(
    id: 'CARD-27',
    cue: [
      '4음 패턴 1–2회 듣기(예: 도-레-미-레).',
      '오르내림 방향을 머릿속 화살표로.',
      '"두-두-두-두"로 같은 윤곽 따라가기.',
      '정확한 음정보다 방향(컨투어) 먼저.',
    ],
    voicedMicroWin: ['4음 컨투어 모방 5회'],
    anatomyEntry: '4음 패턴 듣기',
    anatomyMain: '4음 컨투어 모방',
    anatomyCooldown: '가벼운 하행 허밍',
    maxSustainSec: 2,
    deferredVisualFeedback: true,
    variableAxes: {
      'contour': ['상승', '하강', '아치', '밸리'],
    },
  ),
  'CARD-28': Card(
    id: 'CARD-28',
    cue: [
      '짧은 2–4박 리듬을 손뼉으로 따라치기.',
      '같은 리듬을 "다-다-다"로 말하듯.',
      '같은 리듬을 기준 한 음에 얹어 노래.',
      '세 단계에서 박 위치 흔들림 ❌.',
    ],
    voicedMicroWin: ['손뼉→말→노래 리듬 전이 5회'],
    anatomyEntry: '리듬 손뼉',
    anatomyMain: 'clap-speak-sing 전이',
    anatomyCooldown: '느린 호흡 3회',
    maxSustainSec: 2,
    variableAxes: {
      'pattern': ['따-따-쉼-따', '따-쉼-따-따'],
      'tempo': ['느림', '조금 느림'],
    },
  ),
  'CARD-29': Card(
    id: 'CARD-29',
    cue: [
      '아치(낮-높-낮)를 듣고 "두"로 따라가기.',
      '밸리(높-낮-높)를 듣고 따라가기.',
      '섞여 나와도 방향 헷갈리지 ❌.',
      '음을 미끄러뜨리지 말고 분리해서.',
    ],
    voicedMicroWin: ['아치·밸리 컨투어 구별 모방 5회'],
    anatomyEntry: '두 윤곽 듣기',
    anatomyMain: '아치·밸리 컨투어',
    anatomyCooldown: '가벼운 하행 허밍',
    maxSustainSec: 2,
    deferredVisualFeedback: true,
    variableAxes: {
      'contour': ['아치', '밸리'],
    },
  ),
  // 블록5 곡 조각 전이
  'CARD-30': Card(
    id: 'CARD-30',
    cue: [
      '4음 안팎 짧은 조각을 "음~"(허밍)으로.',
      '같은 조각을 "응"(ng)으로 한 번 더.',
      '같은 조각을 "오~" 모음으로 옮기기.',
      '모음으로 바뀔 때 음정 흔들림 ❌.',
    ],
    voicedMicroWin: ['허밍→모음 전이(음정 유지) 5회'],
    anatomyEntry: '허밍 준비',
    anatomyMain: '허밍/NG→모음 전이',
    anatomyCooldown: '하행 허밍',
    maxSustainSec: 3,
    variableAxes: {
      'vowel': ['오', '우', '아'],
    },
  ),
  'CARD-31': Card(
    id: 'CARD-31',
    cue: [
      '"아·오·우" 중 하나를 기준 음에 2–3초 유지.',
      '모음이 닫히거나 색이 바뀌지 않게.',
      '"나-노-누"처럼 받침 없는 음절 짧게.',
      '자음은 짧게, 모음은 길게.',
    ],
    voicedMicroWin: ['받침 없는 음절 모음 핵 유지 5회'],
    anatomyEntry: '가벼운 모음 1회',
    anatomyMain: '한국어 모음 핵 유지',
    anatomyCooldown: '입 다문 허밍',
    maxSustainSec: 3,
    variableAxes: {
      'syllable': ['나-노-누', '마-모-무'],
      'vowel': ['아', '오', '우'],
    },
  ),
  'CARD-32': Card(
    id: 'CARD-32',
    cue: [
      '짧은 한 프레이즈를 "두~"로 먼저 녹음(준비).',
      '같은 프레이즈를 가사로 녹음.',
      '두 녹음 듣고 무너진 곳 한 곳만 찾기.',
      '가사가 너무 약하면 준비로 돌아가 다시.',
    ],
    voicedMicroWin: ['준비 vs 가사 A/B 비교 1세트'],
    anatomyEntry: '짧은 프레이즈 정하기',
    anatomyMain: '준비 vs 가사 A/B 전이',
    anatomyCooldown: '가벼운 /m/',
    maxSustainSec: 3,
    maxTakeCount: 2,
  ),
  // 블록6 일관성·졸업 산출물
  'CARD-33': Card(
    id: 'CARD-33',
    cue: [
      '사람 목소리 단일음 10개를 음역에 걸쳐 듣기.',
      '각 음을 짧은 상상 후 "두~"로 모방.',
      '밀어 올리지 말고 중심에 안착.',
      '10회 중 몇 회 맞췄는지 저장.',
    ],
    voicedMicroWin: ['단일음 10회 중 8회 매칭 산출물'],
    anatomyEntry: '기준음 듣기',
    anatomyMain: '단일음 8/10 체크포인트',
    anatomyCooldown: '하행 허밍',
    maxSustainSec: 2,
    maxTakeCount: 1,
    deferredVisualFeedback: true,
  ),
  'CARD-34': Card(
    id: 'CARD-34',
    cue: [
      '짧은 프레이즈를 허밍으로 불러보기.',
      '같은 프레이즈를 모음으로 옮기기.',
      '같은 프레이즈를 가사로 불러 녹음.',
      '가사 버전을 전이 산출물로 저장.',
    ],
    voicedMicroWin: ['조각→가사 전이 산출물 1개'],
    anatomyEntry: '짧은 프레이즈 준비',
    anatomyMain: '전이 졸업 산출물(조각→가사)',
    anatomyCooldown: '느린 호흡 3회',
    maxSustainSec: 3,
    maxTakeCount: 1,
  ),
  // R5b 리서치 반영(영역4) — 후두 이완·하행 쿨다운
  'CARD-35': Card(
    id: 'CARD-35',
    cue: [
      '코로 깊이 들이쉬며 하품하듯 목 안을 넓히기.',
      '"하아—" 한숨으로 부드럽게 내쉬기.',
      '설골·갑상연골 주변을 가볍게 원으로(불편하면 즉시 멈춤).',
      '소리는 작게, 목을 풀어주는 느낌만.',
    ],
    voicedMicroWin: ['하품-한숨 이완 3회'],
    anatomyEntry: '하품 자세',
    anatomyMain: '하품-한숨 후두 이완',
    anatomyCooldown: '느린 호흡 3회',
    maxDurationSec: 120,
    maxSustainSec: 4,
    safetyIntensity: 'low',
  ),
  'CARD-36': Card(
    id: 'CARD-36',
    cue: [
      '편안한 중음에서 시작.',
      '허밍이나 빨대로 부드럽게 하행 글라이드.',
      'floaty한 작은 /u/로 마무리.',
      '음량 키우지 말고 이완·정리만.',
    ],
    voicedMicroWin: ['하행 저강도 쿨다운 2–3분'],
    anatomyEntry: '편안한 중음',
    anatomyMain: '하행 저강도 쿨다운',
    anatomyCooldown: '느린 호흡 3회',
    maxDurationSec: 180,
    maxSustainSec: 6,
    safetyIntensity: 'low',
  ),
  // R5c 영역 보강 — 딕션(받침)·온셋(/h 페이딩·자가변별)·공명
  'CARD-37': Card(
    id: 'CARD-37',
    cue: [
      '받침 있는 짧은 단어 정하기(예: 밤·산·강).',
      '음 길이의 앞 8~9할은 모음으로 유지.',
      '마지막에 받침을 짧고 부드럽게 닫기.',
      '받침을 터뜨리지 않기.',
    ],
    voicedMicroWin: ['받침 늦게·짧게 닫기 5회'],
    anatomyEntry: '받침 단어 정하기',
    anatomyMain: '한국어 종성 저부하 처리',
    anatomyCooldown: '입 다문 허밍',
    maxSustainSec: 3,
    variableAxes: {
      'syllable': ['밤', '산', '강', '달'],
    },
  ),
  'CARD-38': Card(
    id: 'CARD-38',
    cue: [
      '긴 "흐—"로 숨 먼저 흘리며 모음 시작(흐-아).',
      '익숙해지면 /h/를 짧게.',
      '거의 들리지 않을 만큼 /h/ 줄이기.',
      '마지막엔 모음만 부드럽게.',
    ],
    voicedMicroWin: ['/h/ 단계 축소 온셋 5회'],
    anatomyEntry: '긴 /h/ 시작',
    anatomyMain: '/h/ 페이딩 → 균형 온셋',
    anatomyCooldown: '가벼운 /m/',
    maxSustainSec: 4,
    variableAxes: {
      'vowel': ['아', '오', '우'],
    },
  ),
  'CARD-39': Card(
    id: 'CARD-39',
    cue: [
      '일부러 숨 섞인 시작 1회 듣기.',
      '깔끔한 균형 시작 1회 듣기.',
      '두 소리 차이만 귀로 구분.',
      '균형 쪽으로 3회 더, 숨섞임은 반복 ❌.',
    ],
    voicedMicroWin: ['숨섞임 vs 균형 시작 구별 5회'],
    anatomyEntry: '두 시작 듣기',
    anatomyMain: '온셋 자가변별',
    anatomyCooldown: '가벼운 허밍',
    maxSustainSec: 3,
    deferredVisualFeedback: true,
  ),
  'CARD-40': Card(
    id: 'CARD-40',
    cue: [
      '/m/ 허밍으로 입술·콧대 앞쪽 울림 찾기.',
      '그 울림을 "음-마"로 모음에 옮기기.',
      '소리를 목 뒤가 아닌 얼굴 앞에 두기.',
      '짜내지 말고 가볍게.',
    ],
    voicedMicroWin: ['전방 공명 → 모음 전이 5회'],
    anatomyEntry: '가벼운 허밍',
    anatomyMain: '전방 공명·플레이스먼트',
    anatomyCooldown: '하행 허밍',
    maxSustainSec: 4,
    variableAxes: {
      'vowel': ['마', '모', '무'],
    },
  ),
  // R5e 호흡 강화(영역3) — 호흡-소리 연결·날숨 페이싱·구문 호흡
  'CARD-41': Card(
    id: 'CARD-41',
    cue: [
      '무성 /sss/ 또는 빨대로 고른 날숨 3초.',
      '같은 흐름 위에 소리 살짝 얹기(s→z 또는 빨대→/u/).',
      '소리가 호흡을 타고 시작되게.',
      '목으로 누르지 말고 흐름 먼저.',
    ],
    voicedMicroWin: ['호흡 흐름 위 소리 얹기 5회'],
    anatomyEntry: '고른 무성 날숨',
    anatomyMain: '호흡-소리 연결(breath-to-tone)',
    anatomyCooldown: '느린 날숨',
    maxSustainSec: 4,
    variableAxes: {
      'vowel': ['z', 'u'],
    },
  ),
  'CARD-42': Card(
    id: 'CARD-42',
    cue: [
      '작은 들숨 후 /sss/ 또는 /vu/로 4박.',
      '강하게 내쉬지 말고 끝까지 고르게.',
      '익숙해지면 6박으로 늘리기.',
      '중간에 끊기면 길이를 줄였다 다시.',
    ],
    voicedMicroWin: ['고른 날숨 4–6박 5회'],
    anatomyEntry: '작은 들숨',
    anatomyMain: '고른 날숨 페이싱',
    anatomyCooldown: '느린 호흡 3회',
    maxSustainSec: 6,
    variableAxes: {
      'phraseLength': ['4박', '6박'],
    },
  ),
  'CARD-43': Card(
    id: 'CARD-43',
    cue: [
      '짧은 4박 구문을 떠올리기.',
      '2박 동안 작게·조용히 들이쉬기, 가득 ❌.',
      '들이쉰 직후 어깨 올라갔는지 확인.',
      '남은 숨 비워 다음 들숨 전 리셋.',
    ],
    voicedMicroWin: ['구문 크기 들숨 5회(어깨 들림 없이)'],
    anatomyEntry: '구문 떠올리기',
    anatomyMain: '구문 크기 호흡(과흡기 방지)',
    anatomyCooldown: '느린 날숨',
    maxDurationSec: 180,
  ),



  // ===== R3 Universal Vocal Core 카드 (UC) =====
  'UC-01': Card(
    id: 'UC-01',
    cue: ['4박 phrase.', '숨을 많이 들이마시지 않기.', '끝은 남기고 편하게.'],
    voicedMicroWin: ['4박 phrase 발성 5회'],
    anatomyEntry: '조용한 들숨',
    anatomyMain: 'Breath Phrase 4-beat',
    anatomyCooldown: '느린 날숨',
    variableAxes: {'phraseLength': ['4박', '6박'], 'vowel': ['m', 'u', 'a']},
  ),
  'UC-02': Card(
    id: 'UC-02',
    cue: ['6박 phrase.', '중간에 무너지지 않기.', '밀지 말고 작게 정리.'],
    voicedMicroWin: ['6박 phrase 4회'],
    anatomyEntry: '늑골-복부 호흡',
    anatomyMain: 'Breath Support 6-beat',
    anatomyCooldown: '가벼운 /m/',
    variableAxes: {'phraseLength': ['6박', '8박'], 'vowel': ['u', 'a']},
  ),
  'UC-03': Card(
    id: 'UC-03',
    cue: ['말하기 → 허밍 → 모음.', '같은 호흡 길이.', '목으로 밀지 않기.'],
    voicedMicroWin: ['speech→hum→vowel 4회'],
    anatomyEntry: '문장 말하기',
    anatomyMain: 'Breath-to-Onset Transfer',
    anatomyCooldown: '호흡 3회',
    variableAxes: {'sentence': ['오늘은 편하게', '조금 더 길게'], 'vowel': ['m', 'u', 'a']},
  ),
  'UC-04': Card(
    id: 'UC-04',
    cue: [
      '가벼운 숨 섞임 1회와 편한 균형 1회 비교.',
      '눌린 예시는 듣기만 하고 따라 하지 않기.',
      '더 편한 take 선택.',
    ],
    voicedMicroWin: ['가벼운 숨 섞임↔균형 onset A/B 3쌍'],
    anatomyEntry: '가벼운 onset 준비',
    anatomyMain: '안전한 Phonation A/B',
    anatomyCooldown: '입 다문 허밍',
    variableAxes: {
      'onset': ['slightly_airy', 'balanced', 'pressed_listening_only'],
      'range': ['중음'],
    },
    allowsToneAB: true,
  ),
  'UC-05': Card(
    id: 'UC-05',
    cue: ['SOVT로 같은 contour.', '빼고 모음으로.', '느낌을 억지로 붙잡지 않기.'],
    voicedMicroWin: ['SOVT→vowel contour 5회'],
    anatomyEntry: 'SOVT 1회',
    anatomyMain: 'SOVT Transfer Contour',
    anatomyCooldown: '가벼운 허밍',
    variableAxes: {'tool': ['straw', 'lip_trill', 'hum'], 'contour': ['저-고-저', '같-고-같']},
  ),
  'UC-06': Card(
    id: 'UC-06',
    cue: ['3–5음 패턴 듣기.', '먼저 화면 없이.', '끝난 뒤만 확인.'],
    voicedMicroWin: ['3–5음 call-response 5회'],
    anatomyEntry: '패턴 듣기',
    anatomyMain: 'Call-Response Pitch',
    anatomyCooldown: '하행 허밍',
    variableAxes: {'length': ['3음', '5음'], 'vowel': ['m', 'u']},
    deferredVisualFeedback: true,
  ),
  'UC-07': Card(
    id: 'UC-07',
    cue: ['반주 위 첫 음 듣기.', '입으로 내기 전에 속으로 한 번.', '작게 따라가기.'],
    voicedMicroWin: ['첫 음 찾기 5회'],
    anatomyEntry: '기준음 듣기',
    anatomyMain: 'Backing Entry Pitch',
    anatomyCooldown: '가벼운 /m/',
    variableAxes: {'entry': ['1박 뒤', '2박 뒤'], 'vowel': ['m', 'u']},
    deferredVisualFeedback: true,
  ),
  'UC-08': Card(
    id: 'UC-08',
    cue: ['쉼표 뒤 들어오기.', '먼저 손가락 탭.', '그다음 허밍.'],
    voicedMicroWin: ['rest-entry rhythm 5회'],
    anatomyEntry: '4박 pulse',
    anatomyMain: 'Rest Entry Timing',
    anatomyCooldown: '호흡 3회',
    variableAxes: {'pattern': ['쉼-음-음-음', '음-쉼-음-음'], 'tempo': ['느림', '중간']},
  ),
  'UC-09': Card(
    id: 'UC-09',
    cue: ['탭 → 허밍 → 음절.', '같은 리듬 유지.', '빨라지면 한 단계 느리게.'],
    voicedMicroWin: ['tap→hum→syllable rhythm 4회'],
    anatomyEntry: '손가락 탭',
    anatomyMain: 'Rhythm Transfer',
    anatomyCooldown: '턱 풀기',
    variableAxes: {'pattern': ['음-음-쉼-음', '음-쉼-음-음'], 'syllable': ['마', '나']},
  ),
  'UC-10': Card(
    id: 'UC-10',
    cue: ['같은 음에서 밝게·따뜻하게.', '입·혀를 과하게 쓰지 않기.', '정답 톤 없음.'],
    voicedMicroWin: ['timbre contrast 5회'],
    anatomyEntry: '편한 기준음',
    anatomyMain: 'Resonance & Timbre Control',
    anatomyCooldown: '편한 모음 허밍',
    variableAxes: {'tone': ['bright', 'warm', 'clear'], 'vowel': ['i', 'o', 'a']},
    timbreTags: ['brightWarm', 'filter', 'comfort'],
    allowsToneAB: true,
  ),
  'UC-11': Card(
    id: 'UC-11',
    cue: ['/m/에서 모음으로.', '비음 느낌을 밀지 않기.', '선명함과 편안함 비교.'],
    voicedMicroWin: ['nasal-to-oral clarity 5회'],
    anatomyEntry: '가벼운 /m/',
    anatomyMain: 'Oral Clarity Transfer',
    anatomyCooldown: '가벼운 /u/',
    variableAxes: {'bridge': ['m-a', 'n-a', 'ng-a'], 'tone': ['clear', 'soft']},
    timbreTags: ['clarity', 'oral', 'comfort'],
    allowsToneAB: true,
  ),
  'UC-12': Card(
    id: 'UC-12',
    cue: [
      '짧은 목표 음 1–3음 듣기.',
      '즉시 따라 부르고 녹음으로 오차 확인.',
      '항상 높음/낮음/끝 흐름 중 무엇인지 라벨.',
      'Flat이면 더 높게, Sharp면 더 낮게 재시도.',
    ],
    voicedMicroWin: ['오차 유형 라벨 후 2차 교정 1쌍'],
    anatomyEntry: '목표 음 듣기',
    anatomyMain: 'Auditory-Motor Pitch Correction',
    anatomyCooldown: '가벼운 허밍',
    deferredVisualFeedback: true,
  ),
  'UC-13': Card(
    id: 'UC-13',
    cue: ['편한 음역 지도.', '오늘은 확장하지 않고 기록만.', '무리한 고음 금지.'],
    voicedMicroWin: ['usable range mapping 1세트'],
    anatomyEntry: '가벼운 허밍',
    anatomyMain: 'Usable Range Map',
    anatomyCooldown: '하행 허밍',
    variableAxes: {'range': ['편한 하한', '편한 상한'], 'vowel': ['m', 'u']},
    deferredVisualFeedback: true,
    safetyIntensity: 'moderate',
  ),
  'UC-14': Card(
    id: 'UC-14',
    cue: ['레지스터 변화 지점만 표시.', '없애지 않기.', '다음엔 더 작게.'],
    voicedMicroWin: ['register observation 3회'],
    anatomyEntry: '작은 글라이드',
    anatomyMain: 'Register Observation',
    anatomyCooldown: 'SOVT 1회',
    variableAxes: {'glide': ['작은 5도', '작은 옥타브 아래'], 'vowel': ['u', 'm']},
    deferredVisualFeedback: true,
    safetyIntensity: 'moderate',
  ),
  'UC-15': Card(
    id: 'UC-15',
    cue: ['자음이 박자보다 앞서거나 늦지 않게.', '작게 말하고 허밍.', '가사 한 줄에 적용.'],
    voicedMicroWin: ['consonant timing 5회'],
    anatomyEntry: '리듬 말하기',
    anatomyMain: 'Consonant Timing',
    anatomyCooldown: '턱·혀 풀기',
    variableAxes: {'consonant': ['m/n', 't/k', '받침'], 'tempo': ['느림', '중간']},
  ),
  'UC-16': Card(
    id: 'UC-16',
    cue: ['중립 4마디.', '가사 말하기 → 리듬 말하기.', '한 음으로 노래.'],
    voicedMicroWin: ['neutral phrase application 1세트'],
    anatomyEntry: '가사 말하기',
    anatomyMain: 'Repertoire Application Entry',
    anatomyCooldown: '호흡 3회',
    variableAxes: {'step': ['말하기', '리듬 말하기', '한 음 노래'], 'phrase': ['중립 4마디']},
    allowsToneAB: true,
  ),
  'UC-17': Card(
    id: 'UC-17',
    cue: ['같은 조건으로 짧은 표준샘플.', '점수 없이 전후 비교.', '오늘 태그 하나만 기록.'],
    voicedMicroWin: ['Universal Core checkpoint sample'],
    anatomyEntry: '환경 확인',
    anatomyMain: 'Core Checkpoint Sample',
    anatomyCooldown: '가벼운 허밍',
    timbreTags: ['checkpoint', 'selfTag', 'recordingStandard'],
    toneGoal: '공통 코어 진행 중 음색·피치·리듬 기준을 주기적으로 비교한다.',
    allowsToneAB: true,
    requiresSameRecordingCondition: true,
  ),

  // ===== v9 Universal Core 나선형 보강 카드 =====
  'UC-18': Card(
    id: 'UC-18',
    cue: [
      '숨 위치를 먼저 표시.',
      '4–8박 phrase를 편하게.',
      '짧고 조용하게 다시 들이쉬기.',
      '끝에 여유를 남기기.',
    ],
    voicedMicroWin: ['phrase→짧은 갱신 호흡→phrase 3세트'],
    anatomyEntry: '호흡 위치 표시',
    anatomyMain: 'Breath Renewal & Phrase Landing',
    anatomyCooldown: '느린 날숨 2회',
    variableAxes: {
      'phraseLength': ['4박', '6박', '8박'],
      'renewal': ['한 번', '두 번'],
    },
  ),
  'UC-19': Card(
    id: 'UC-19',
    cue: [
      '세 음을 듣기.',
      '2초 조용히 떠올리기.',
      '화면 없이 한 번 따라가기.',
      '새 시작음에서도 같은 모양.',
    ],
    voicedMicroWin: ['3음 기억→새 시작음 전이 4회'],
    anatomyEntry: '패턴 듣기',
    anatomyMain: 'Pitch Memory & Transposition',
    anatomyCooldown: '가벼운 하행 허밍',
    variableAxes: {
      'contour': ['상행', '하행', '저-고-저'],
      'startShift': ['낮게', '높게'],
    },
    deferredVisualFeedback: true,
  ),
  'UC-20': Card(
    id: 'UC-20',
    cue: [
      '4박을 손가락으로 나누기.',
      '4분음표·8분음표·쉼표를 탭.',
      '허밍으로 같은 리듬.',
      '마지막에 음절로.',
    ],
    voicedMicroWin: ['tap→hum→syllable 리듬 4세트'],
    anatomyEntry: 'pulse 탭',
    anatomyMain: 'Subdivision & Duration',
    anatomyCooldown: '무성 탭 1세트',
    variableAxes: {
      'subdivision': ['4분음표', '8분음표', '쉼표'],
      'tempo': ['느림', '중간'],
    },
  ),
  'UC-21': Card(
    id: 'UC-21',
    cue: [
      '같은 모음으로 3–5음.',
      '피치와 박자 유지.',
      '모음 하나만 바꾸기.',
      '턱은 크게 움직이지 않기.',
    ],
    voicedMicroWin: ['같은 contour의 모음 전환 4회'],
    anatomyEntry: '편한 모음 1회',
    anatomyMain: 'Vowel Continuity',
    anatomyCooldown: '편한 모음 허밍',
    variableAxes: {
      'vowelPair': ['u-a', 'i-e', 'o-a'],
      'length': ['3음', '5음'],
    },
    allowsToneAB: true,
  ),
  'UC-22': Card(
    id: 'UC-22',
    cue: [
      '같은 짧은 phrase를 낮은 key부터.',
      '현재 key와 한 단계 높은 key도 짧게.',
      '최고음보다 편한 key 선택.',
      '오늘의 usable key를 기록.',
    ],
    voicedMicroWin: ['낮음·현재·높음 중 편한 key 선택 1세트'],
    anatomyEntry: '가벼운 허밍',
    anatomyMain: 'Key Fit Choice',
    anatomyCooldown: '선택한 key에서 하행 허밍',
    variableAxes: {
      'keyOption': ['낮음', '현재', '한 단계 높음'],
      'phraseLength': ['2마디', '4마디'],
    },
    deferredVisualFeedback: true,
    safetyIntensity: 'moderate',
    maxTakeCount: 3,
  ),
  'UC-23': Card(
    id: 'UC-23',
    cue: [
      '핵심 단어 하나 고르기.',
      '말로 먼저 전달.',
      '같은 의도로 짧게 노래.',
      '크게보다 phrase 모양을 바꾸기.',
    ],
    voicedMicroWin: ['말하기→노래 phrase arc 3회'],
    anatomyEntry: '핵심 단어 말하기',
    anatomyMain: 'Phrase Arc & Intention',
    anatomyCooldown: '가벼운 말하기 1회',
    variableAxes: {
      'intent': ['calm', 'clear', 'warm', 'forward'],
      'phraseShape': ['앞 강조', '중간 확장', '끝 정리'],
    },
    allowsToneAB: true,
  ),
  'UC-24': Card(
    id: 'UC-24',
    cue: [
      'SOVT로 짧은 contour.',
      '같은 모양을 열린 모음으로.',
      '마지막에 가사 한 줄.',
      '첫 시도는 화면 없이.',
    ],
    voicedMicroWin: ['SOVT→모음→가사 전이 3세트'],
    anatomyEntry: '낮은 부하 SOVT',
    anatomyMain: 'SOVT Transfer Probe',
    anatomyCooldown: 'SOVT 1회',
    variableAxes: {
      'tool': ['straw', 'lip_trill', 'hum'],
      'target': ['모음', '음절', '가사 한 줄'],
    },
    deferredVisualFeedback: true,
  ),
  'UC-25': Card(
    id: 'UC-25',
    cue: [
      '모델 없이 첫 시도.',
      '내 결과에서 바꿀 점 하나 선택.',
      '두 번째 시도는 한 번만.',
      '더 편한 take를 남기기.',
    ],
    voicedMicroWin: ['독립 시도→자기 cue→재시도 1쌍'],
    anatomyEntry: '과제 확인',
    anatomyMain: 'Self-Coaching Retrieval',
    anatomyCooldown: '짧은 자기평가',
    variableAxes: {
      'review': ['pitch', 'rhythm', 'tone', 'phrase'],
      'attempts': ['첫 시도', '재시도'],
    },
    allowsToneAB: true,
    maxTakeCount: 2,
  ),

  // ===== R5d 중급 확장 카드(UC-26~41) — 리서치 영역 심화 =====
  'UC-26': Card(
    id: 'UC-26',
    cue: [
      '다음 구문이 4박인지 8박인지 확인.',
      '어깨 들지 말고 갈비뼈만 조용히 벌리기.',
      '한 호흡으로 구문 끝까지 균등하게.',
      '짧은 구문엔 작게 들이쉬기.',
    ],
    voicedMicroWin: ['구문 크기 맞춘 한 호흡 완주 5회'],
    anatomyEntry: '조용한 들숨',
    anatomyMain: 'Phrase-Fit Breath Gauge',
    anatomyCooldown: '느린 날숨',
    maxSustainSec: 8,
  ),
  'UC-27': Card(
    id: 'UC-27',
    cue: [
      '"즈—" 또는 "브이—"를 앞쪽 buzz로 3초.',
      '소리 켜진 그대로 모음으로(즈-아).',
      '세게 밀지 말고 같은 ease로.',
      '/v/·/z/·허밍 중 가장 쉬운 걸 기록.',
    ],
    voicedMicroWin: ['유성 마찰음→모음 clean onset 5회'],
    anatomyEntry: '가벼운 마찰음',
    anatomyMain: 'Voiced-Fricative Onset Ladder',
    anatomyCooldown: '가벼운 /m/',
    maxSustainSec: 3,
  ),
  'UC-28': Card(
    id: 'UC-28',
    cue: [
      '편한 음에서 빨대/립트릴 20–30초.',
      '도구 떼고 즉시 /u/ 1–2초.',
      '강도 올리지 말고 /a/로 1초 전이.',
      '다시 빨대로 리셋 후 반복.',
    ],
    voicedMicroWin: ['SOVT→개방모음 스냅 전이 5회'],
    anatomyEntry: 'SOVT 준비',
    anatomyMain: 'SOVT-to-Open-Vowel Transfer',
    anatomyCooldown: '하행 허밍',
    maxSustainSec: 3,
  ),
  'UC-29': Card(
    id: 'UC-29',
    cue: [
      '/mi/에서 콧등·윗입술 진동 가볍게 찾기.',
      '진동 만들려 압력 올리지 않기.',
      '코 살짝 막아 음색 과하게 변하면 줄이기.',
      '짧은 단어로 같은 감각 유지.',
    ],
    voicedMicroWin: ['전방 진동 유지·과비성 없음 확인'],
    anatomyEntry: '가벼운 /mi/',
    anatomyMain: 'Resonant Mask Calibration',
    anatomyCooldown: '가벼운 허밍',
    maxSustainSec: 4,
  ),
  'UC-30': Card(
    id: 'UC-30',
    cue: [
      '목표 음을 아래에서 글라이드로 접근.',
      '같은 음을 위에서 글라이드로 접근.',
      '두 방향 effort 비교.',
      '더 쉬운 접근 방향 기록.',
    ],
    voicedMicroWin: ['한 음 양방향 접근 비교 3세트'],
    anatomyEntry: '편한 anchor',
    anatomyMain: 'Bidirectional Approach Glide',
    anatomyCooldown: '하행 글라이드',
    maxSustainSec: 2,
    deferredVisualFeedback: true,
  ),
  'UC-31': Card(
    id: 'UC-31',
    cue: [
      'passaggio 근처 편한 모음 하나.',
      '3도→5도 천천히 상행 후 하행.',
      '"더 단단하게" 버전과 "더 가볍게" 버전.',
      '두 음색 차이와 변하는 지점 관찰.',
    ],
    voicedMicroWin: ['단단함↔가벼움 음색 구별·전환 인지'],
    anatomyEntry: '편한 모음',
    anatomyMain: 'Register Observation Glide',
    anatomyCooldown: '하행 허밍',
    maxSustainSec: 2,
    deferredVisualFeedback: true,
    safetyIntensity: 'moderate',
  ),
  'UC-32': Card(
    id: 'UC-32',
    cue: [
      '글라이드를 녹음.',
      '브레이크 난 대략 음고를 화면에 태그.',
      '음량·모음·템포 바꿔 재현하며 비교.',
      '실패가 아니라 데이터로 보기.',
    ],
    voicedMicroWin: ['두 글라이드에서 전환 구간 태그'],
    anatomyEntry: '편한 글라이드',
    anatomyMain: 'Passaggio Stability Tracking',
    anatomyCooldown: '느린 호흡 3회',
    maxSustainSec: 2,
    safetyIntensity: 'moderate',
  ),
  'UC-33': Card(
    id: 'UC-33',
    cue: [
      '상행 중 전환 징후 느끼면 즉시 멈추기.',
      '음량 줄여 같은 구간 다시 접근.',
      '안 되면 하행 재접근·범위 축소·SOVT 리셋·조옮김.',
      '선택한 전략 결과 기록.',
    ],
    voicedMicroWin: ['전환 징후에 push 대신 대안 선택'],
    anatomyEntry: '편한 anchor',
    anatomyMain: 'Safe Transition Response',
    anatomyCooldown: '하행 글라이드',
    maxSustainSec: 2,
    safetyIntensity: 'moderate',
  ),
  'UC-34': Card(
    id: 'UC-34',
    cue: [
      '같은 편한 음에서 ㅣ-ㅔ-ㅏ-ㅗ-ㅜ 차례로.',
      '각 모음의 밝기/따뜻함 듣고 태그.',
      '작은 볼륨에서 밝은 톤 vs 둥근 톤 비교.',
      '가장 선명·편한 조합 기록.',
    ],
    voicedMicroWin: ['모음 색채 구별·선호 기록'],
    anatomyEntry: '가벼운 모음',
    anatomyMain: 'Vowel Color Ladder',
    anatomyCooldown: '하행 허밍',
    maxSustainSec: 3,
  ),
  'UC-35': Card(
    id: 'UC-35',
    cue: [
      '머리 쪽 가벼운 소리에서 시작해 5음 음계로 내려오기.',
      '가슴 쪽으로 끌어내리지 말고 가벼움 유지.',
      '무거워지기 직전까지만 내려가 그 경계를 조금씩 넓히기.',
      '브레이크 나면 SOVT로 부하 낮춰 다시.',
    ],
    voicedMicroWin: ['머리→중간 하행 연결 브레이크 감소'],
    anatomyEntry: '가벼운 머리소리',
    anatomyMain: 'Mix-Entry (위에서 내려오기)',
    anatomyCooldown: '하행 허밍',
    maxSustainSec: 3,
    safetyIntensity: 'moderate',
  ),
  'UC-36': Card(
    id: 'UC-36',
    cue: [
      '가사 한 문장을 리듬·강세 살려 말하기.',
      '같은 리듬으로 2–3음만 음고 부여.',
      '5도 범위로 확장 후 멜로디 연결.',
      '부르지 말고 말하듯, 목 압박만 줄이기.',
    ],
    voicedMicroWin: ['말→노래 전이 음색·자음 유지'],
    anatomyEntry: '가사 말하기',
    anatomyMain: 'Speech-to-Song Bridge',
    anatomyCooldown: '가벼운 /m/',
    maxSustainSec: 4,
    safetyIntensity: 'moderate',
  ),
  'UC-37': Card(
    id: 'UC-37',
    cue: [
      '으뜸음 한 번 듣기.',
      '두 음(예: 도-미) 듣고 방향 말하기.',
      '화면 없이 둘째 음만 따라 부르기.',
      '시작음 바꿔 같은 도약 반복.',
    ],
    voicedMicroWin: ['3도·5도 도약 모방 4세트'],
    anatomyEntry: '으뜸음 듣기',
    anatomyMain: 'Interval Leap Imitation',
    anatomyCooldown: '하행 허밍',
    maxSustainSec: 2,
    deferredVisualFeedback: true,
  ),
  'UC-38': Card(
    id: 'UC-38',
    cue: [
      '으뜸음 큐 듣기.',
      '5음 상행/하행 음계 한 번 듣기.',
      '화면 없이 첫 시도로 따라 부르기.',
      '인접 조에서 같은 음계 반복.',
    ],
    voicedMicroWin: ['5음 음계 첫 시도 3세트'],
    anatomyEntry: '으뜸음 큐',
    anatomyMain: 'Five-Tone Scale Imitation',
    anatomyCooldown: '하행 허밍',
    maxSustainSec: 2,
    deferredVisualFeedback: true,
    safetyIntensity: 'moderate',
  ),
  'UC-39': Card(
    id: 'UC-39',
    cue: [
      '2·4박에 메트로놈.',
      '쉼표 한 박 뒤 진입 연습.',
      '1마디 당김음 패턴 따라(echo) 부르기.',
      'click 빼고 같은 패턴 유지.',
    ],
    voicedMicroWin: ['당김음 1마디 echo 3세트'],
    anatomyEntry: '박 느끼기',
    anatomyMain: 'Syncopation & Off-Beat Entry',
    anatomyCooldown: '느린 호흡 3회',
    maxSustainSec: 4,
  ),
  'UC-40': Card(
    id: 'UC-40',
    cue: [
      '가사를 표기형→발음형으로(예: 꽃잎이→꼰니피).',
      '자음 이동을 화살표로 표시.',
      '음절 끊지 말고 다음 모음으로 연결.',
      '규칙별 예문 3개씩 녹음 확인.',
    ],
    voicedMicroWin: ['연음·비음화·된소리 예문 확인'],
    anatomyEntry: '가사 전사',
    anatomyMain: 'Phonological Change in Phrase',
    anatomyCooldown: '입 다문 허밍',
    maxSustainSec: 6,
  ),
  'UC-41': Card(
    id: 'UC-41',
    cue: [
      '숨 위치를 먼저 표시.',
      '느린 템포로 가사+멜로디.',
      '목표 템포로 올리기.',
      '한 호흡으로 프레이즈 끝까지.',
    ],
    voicedMicroWin: ['2–4마디 통합 프레이즈 2회 완주'],
    anatomyEntry: '숨 위치 표시',
    anatomyMain: 'Lyric Phrase Integration',
    anatomyCooldown: '느린 날숨',
    maxSustainSec: 6,
    safetyIntensity: 'moderate',
  ),
  // R5f 중급 리서치 반영 — 음역 도징·셋잇단·구간 전환
  'UC-42': Card(
    id: 'UC-42',
    cue: [
      '편한 경계음에서 가볍게 반음만 위/아래 시도.',
      '음량 키우지 말고 SOVT로 부드럽게.',
      '통증·삑사리 나면 즉시 멈추고 경계로 복귀.',
      '새 음은 다음날 회복 확인 전엔 "사용 가능"으로 치지 않기.',
    ],
    voicedMicroWin: ['경계음 ±1반음 안전 탐색 1세트'],
    anatomyEntry: '편한 경계음',
    anatomyMain: 'Safe Range Extension (1~2반음)',
    anatomyCooldown: '하행 글라이드',
    maxSustainSec: 2,
    safetyIntensity: 'moderate',
  ),
  'UC-43': Card(
    id: 'UC-43',
    cue: [
      '4박을 손가락으로 나누기.',
      '한 박을 셋으로(셋잇단) 탭으로 느끼기.',
      '허밍으로 같은 셋잇단.',
      '마지막에 음절로 옮기기.',
    ],
    voicedMicroWin: ['셋잇단 tap→hum→음절 3세트'],
    anatomyEntry: '박 나누기',
    anatomyMain: 'Triplet Subdivision',
    anatomyCooldown: '느린 호흡 3회',
    maxSustainSec: 2,
  ),
  'UC-44': Card(
    id: 'UC-44',
    cue: [
      'verse와 chorus의 평균 높이(테시투라)를 비교.',
      'verse는 가볍게 시작해 에너지 아끼기.',
      'chorus 직전 호흡 리셋.',
      'chorus는 음량이 아니라 공명·앞쪽 배치로.',
    ],
    voicedMicroWin: ['절→후렴 한 줄씩 연결 2회'],
    anatomyEntry: '테시투라 비교',
    anatomyMain: 'Section Transition (verse→chorus)',
    anatomyCooldown: '하행 허밍',
    maxSustainSec: 4,
    safetyIntensity: 'moderate',
  ),

  // ===== v15 음색 조절·재현 카드 (TONE) =====
  'TONE-01': Card(
    id: 'TONE-01',
    cue: [
      '같은 기기·거리·방에서 기준 녹음.',
      '/a/ /i/ /u/ 각 3초.',
      '짧은 문장을 말하듯 녹음.',
      '점수 대신 태그를 고르기.',
    ],
    voicedMicroWin: ['Tone Snapshot Lite: 모음 3종 + 문장 1줄 녹음'],
    anatomyEntry: '녹음 환경·휴대폰 거리 확인',
    anatomyMain: '기준 음색 녹음과 자기 태그',
    anatomyCooldown: '가벼운 허밍 1회',
    variableAxes: {
      'vowel': ['a', 'i', 'u'],
      'tag': ['clean', 'bright', 'warm', 'clear', 'soft', 'round'],
    },
    timbreTags: ['snapshot', 'selfTag', 'recordingStandard'],
    timbreLayer: 'learningSafety',
    toneTagOptions: [
      'comfortable', 'clean', 'bright', 'warm', 'clear', 'soft', 'round', 'tired',
    ],
    toneGoal: '내 목소리 기준선을 만들고 같은 조건에서 비교한다.',
    allowsToneAB: true,
    requiresSameRecordingCondition: true,
    acousticFeedbackLevel: 'ab',
    maxTakeCount: 1,
    maxDurationSec: 60,
    maxSustainSec: 3,
  ),
  'TONE-02': Card(
    id: 'TONE-02',
    cue: [
      '/m/ 2초.',
      '입을 크게 벌리지 말고 /ma/로 열기.',
      '/n/→/na/, /ng/→/a/도 작게.',
      '편안함을 먼저 고르기.',
    ],
    voicedMicroWin: ['Hum-to-Vowel 전이 5회'],
    anatomyEntry: '가벼운 허밍',
    anatomyMain: '비자음/허밍 → 모음 전이',
    anatomyCooldown: '입 다문 /m/ 하행',
    variableAxes: {
      'bridge': ['m-ma', 'n-na', 'ng-a'],
      'range': ['편한 중음', '약간 낮게'],
    },
    timbreTags: ['humToVowel', 'clarity', 'comfort'],
    timbreLayer: 'filter',
    toneTagOptions: ['comfortable', 'clean', 'clear', 'soft', 'round'],
    toneGoal: '허밍의 편안함을 모음으로 옮긴다.',
    allowsToneAB: true,
    maxReps: 5,
    maxDurationSec: 90,
    maxTakeCount: 2,
  ),
  'TONE-03': Card(
    id: 'TONE-03',
    cue: [
      '같은 편한 음에서 모음만 바꾸기.',
      '/i-e-a-o-u/를 천천히.',
      '밝게 느껴지는 모음과 편한 모음 고르기.',
      '고음으로 밀지 않기.',
    ],
    voicedMicroWin: ['Vowel Color Taste 5회'],
    anatomyEntry: '편한 기준음 1회',
    anatomyMain: '모음 색채 비교',
    anatomyCooldown: '편한 모음으로 허밍',
    variableAxes: {
      'vowel': ['i-e-a-o-u', 'u-o-a-e-i'],
      'tag': ['bright', 'warm', 'clear', 'round'],
    },
    timbreTags: ['vowelColor', 'brightWarm', 'selfTag'],
    timbreLayer: 'filter',
    toneTagOptions: ['comfortable', 'bright', 'warm', 'clear', 'round'],
    toneGoal: '모음 변화가 음색에 주는 차이를 듣는다.',
    allowsToneAB: true,
    maxReps: 5,
    maxDurationSec: 90,
    maxTakeCount: 2,
  ),
  'TONE-04': Card(
    id: 'TONE-04',
    cue: [
      '/v/ 또는 /z/ 2초.',
      '같은 느낌으로 모음 열기.',
      '숨이 과하게 새지 않는 편한 시작 찾기.',
      '목을 꽉 잡는 느낌이면 중단.',
    ],
    voicedMicroWin: ['편한 시작 A/B 4회'],
    anatomyEntry: '유성 마찰음 준비',
    anatomyMain: '숨섞임 느낌과 또렷함 사이의 편한 시작',
    anatomyCooldown: '가벼운 /m/',
    variableAxes: {
      'onset': ['v-a', 'z-a', 'm-a'],
      'range': ['편한 중음'],
    },
    timbreTags: ['sourceResult', 'onset', 'comfort'],
    timbreLayer: 'source',
    toneTagOptions: [
      'comfortable', 'clean', 'clear', 'soft', 'airyFeeling', 'effortfulFeeling',
    ],
    toneGoal: '생리 상태를 판정하지 않고 편한 시작의 들리는 결과를 비교한다.',
    allowsToneAB: true,
    acousticFeedbackLevel: 'basic',
    maxReps: 4,
    maxDurationSec: 75,
    maxTakeCount: 2,
    fallbackCardId: 'TONE-02',
  ),
  'TONE-05': Card(
    id: 'TONE-05',
    cue: [
      '짧은 단어를 말하듯 시작.',
      '같은 높이 느낌으로 2초 노래하기.',
      '치지 않고 시작.',
      '목이 맞는 느낌이면 바로 쉬기.',
    ],
    voicedMicroWin: ['Gentle Onset Lab 4회'],
    anatomyEntry: '말하듯 짧은 단어',
    anatomyMain: '말소리 → 노래소리 gentle onset',
    anatomyCooldown: '느린 호흡 3회',
    variableAxes: {
      'syllable': ['나', '마', '오늘', '편하게'],
      'range': ['편한 중음'],
    },
    timbreTags: ['gentleOnset', 'speechLike', 'comfort'],
    timbreLayer: 'source',
    toneTagOptions: ['comfortable', 'clean', 'soft', 'speechLike', 'clear', 'effortfulFeeling'],
    toneGoal: '소리 시작점의 음색을 부드럽고 재현 가능하게 만든다.',
    allowsToneAB: true,
    maxReps: 4,
    maxDurationSec: 75,
    maxTakeCount: 2,
    fallbackCardId: 'TONE-02',
  ),
  'TONE-06': Card(
    id: 'TONE-06',
    cue: [
      '같은 음에서 /i/와 /o/ 비교.',
      '밝은 느낌과 둥근 느낌을 작게 바꿔보기.',
      '입·혀 힘을 과하게 쓰지 않기.',
      '정답 톤 없음.',
    ],
    voicedMicroWin: ['Vowel Color Switch 5회'],
    anatomyEntry: '편한 기준음',
    anatomyMain: '밝기/따뜻함을 모음으로 바꾸기',
    anatomyCooldown: '편한 모음으로 /m/',
    variableAxes: {
      'vowelPair': ['i-o', 'e-u', 'a-o'],
      'tag': ['bright', 'warm', 'round', 'clear'],
    },
    timbreTags: ['vowelSwitch', 'brightWarm', 'filter'],
    timbreLayer: 'filter',
    toneTagOptions: ['comfortable', 'bright', 'warm', 'clear', 'round'],
    toneGoal: '성도/모음 조절로 음색 선택지를 만든다.',
    allowsToneAB: true,
    maxReps: 5,
    maxDurationSec: 90,
    maxTakeCount: 2,
  ),
  'TONE-07': Card(
    id: 'TONE-07',
    cue: [
      '같은 문장을 밝게 1회.',
      '같은 문장을 따뜻하게 1회.',
      '더 좋은 톤 대신 더 편한 take 고르기.',
      '크게 하지 않기.',
    ],
    voicedMicroWin: ['Bright/Warm A/B 1쌍'],
    anatomyEntry: '문장 말하기',
    anatomyMain: '밝은 톤·따뜻한 톤 A/B',
    anatomyCooldown: '가벼운 허밍',
    variableAxes: {
      'phrase': ['오늘은 편하게', '기다려', '괜찮아'],
      'tone': ['bright', 'warm'],
    },
    timbreTags: ['brightWarmAB', 'selfChoice', 'comfort'],
    timbreLayer: 'filter',
    toneTagOptions: ['comfortable', 'bright', 'warm', 'clear', 'round'],
    toneSequence: ['bright', 'warm'],
    toneGoal: '음색을 점수화하지 않고 선택·재현하는 능력을 만든다.',
    allowsToneAB: true,
    requiresSameRecordingCondition: true,
    maxReps: 2,
    maxDurationSec: 90,
    maxTakeCount: 2,
  ),
  'TONE-08': Card(
    id: 'TONE-08',
    cue: [
      '작게 → 중간 → 조금 크게 → 다시 작게.',
      '조금 크게까지만.',
      '음량 점수 없음.',
      '목이 피곤하면 생략.',
    ],
    voicedMicroWin: ['Dynamic Tone Ladder 3회'],
    anatomyEntry: '작은 소리 1회',
    anatomyMain: '작은 범위의 다이내믹에서 톤 유지',
    anatomyCooldown: '작게 /m/ 1회',
    variableAxes: {
      'level': ['p-mp-mf-mp', 'p-mp-p'],
      'vowel': ['u', 'a'],
    },
    timbreTags: ['dynamic', 'toneStability', 'effort'],
    timbreLayer: 'source',
    toneTagOptions: ['comfortable', 'clean', 'soft', 'clear', 'effortfulFeeling'],
    toneGoal: '큰 소리 경쟁이 아니라 작은 범위에서 톤을 유지한다.',
    allowsToneAB: true,
    safetyIntensity: 'moderate',
    maxReps: 3,
    maxDurationSec: 120,
    maxTakeCount: 2,
    weeklyCap: 2,
    fallbackCardId: 'TONE-02',
  ),
  'TONE-09': Card(
    id: 'TONE-09',
    cue: [
      '작은 /u/ 글라이드.',
      '중간에서 소리가 바뀌는 지점만 관찰.',
      'break를 없애려고 밀지 않기.',
      '고음 도전 아님.',
    ],
    voicedMicroWin: ['Register Tone Continuity 5회'],
    anatomyEntry: '편한 /u/',
    anatomyMain: '레지스터 전환 중 톤 변화 관찰',
    anatomyCooldown: '하행 허밍',
    variableAxes: {
      'glide': ['작은 상행', '작은 하행', '3음 상하행'],
      'vowel': ['u', 'm'],
    },
    timbreTags: ['registration', 'toneContinuity', 'rangeSafe'],
    timbreLayer: 'source',
    toneTagOptions: ['comfortable', 'clean', 'soft', 'round', 'effortfulFeeling'],
    toneGoal: '전환 구간의 톤 변화를 안전하게 관찰한다.',
    deferredVisualFeedback: true,
    safetyIntensity: 'moderate',
    maxReps: 5,
    maxDurationSec: 90,
    maxTakeCount: 2,
    weeklyCap: 3,
    fallbackCardId: 'TONE-02',
  ),
  'TONE-10': Card(
    id: 'TONE-10',
    cue: [
      '짧은 한국어 hook을 천천히.',
      '받침은 작고 짧게.',
      '자음에서 목 잠그지 않기.',
      '가사가 더 잘 들리는 take 고르기.',
    ],
    voicedMicroWin: ['Diction Clean Hook 5회'],
    anatomyEntry: '한국어 음절 준비',
    anatomyMain: '한국어 딕션과 음색 명료도',
    anatomyCooldown: '입 다문 허밍',
    variableAxes: {
      'phrase': ['오늘도', '기다려', '괜찮아', '사랑해'],
      'tone': ['clear', 'soft'],
    },
    timbreTags: ['koreanDiction', 'clarity', 'hook'],
    timbreLayer: 'style',
    toneTagOptions: ['comfortable', 'clean', 'clear', 'soft', 'speechLike'],
    toneGoal: '자음·받침이 톤을 끊지 않게 한다.',
    allowsToneAB: true,
    maxReps: 5,
    maxDurationSec: 90,
    maxTakeCount: 2,
  ),
  'TONE-11': Card(
    id: 'TONE-11',
    cue: [
      '화면에 안내된 시작 거리에서 한 번.',
      'clipping이면 조금 멀리, 소음이면 조금 가까이.',
      '같은 문장을 다시 녹음.',
      '편하고 또렷한 조건을 기록.',
    ],
    voicedMicroWin: ['Mic Tone Check A/B 1쌍'],
    anatomyEntry: '휴대폰 거리 확인',
    anatomyMain: '마이크 거리와 녹음 친화 톤 비교',
    anatomyCooldown: '작은 /m/',
    variableAxes: {
      'distance': ['기기별 시작 거리', 'clipping 시 조금 멀리', 'noise 시 조금 가까이'],
      'phrase': ['짧은 문장', '4마디 phrase'],
    },
    timbreTags: ['micTone', 'recording', 'distance'],
    timbreLayer: 'learningSafety',
    toneTagOptions: ['comfortable', 'clean', 'clear', 'soft', 'micFriendly'],
    toneGoal: '고정 거리 점수가 아니라 기기별 편한 녹음 조건을 찾는다.',
    allowsToneAB: true,
    requiresSameRecordingCondition: true,
    maxReps: 2,
    maxDurationSec: 90,
    maxTakeCount: 2,
  ),
  'TONE-12': Card(
    id: 'TONE-12',
    cue: [
      '같은 phrase를 clean으로.',
      '같은 phrase를 warm으로.',
      '같은 phrase를 speech-like로.',
      '편하고 전달되는 take 고르기.',
    ],
    voicedMicroWin: ['Same Phrase Three Tones A/B/C'],
    anatomyEntry: 'phrase 말하기',
    anatomyMain: '동일 phrase의 3톤 비교',
    anatomyCooldown: '편한 톤으로 허밍',
    variableAxes: {
      'tone': ['clean', 'warm', 'speech_like'],
      'phraseLength': ['2마디', '4마디'],
    },
    timbreTags: ['phraseTone', 'clean', 'warm', 'speechLike'],
    timbreLayer: 'style',
    toneTagOptions: ['comfortable', 'clean', 'warm', 'speechLike', 'clear'],
    toneSequence: ['clean', 'warm', 'speechLike'],
    toneGoal: '곡의 의도에 맞게 톤을 선택하고 재현한다.',
    allowsToneAB: true,
    requiresSameRecordingCondition: true,
    maxReps: 3,
    maxDurationSec: 120,
    maxTakeCount: 3,
  ),
  'TONE-13': Card(
    id: 'TONE-13',
    cue: [
      '장르 목표 톤을 하나 고르기.',
      '10–20초 phrase만.',
      '원곡자 복제 금지.',
      '불편하면 즉시 light-mode.',
    ],
    voicedMicroWin: ['Genre Tone Lab 짧은 phrase 최대 3회'],
    anatomyEntry: '장르 tone goal 선택',
    anatomyMain: '장르별 음색 참조를 짧은 phrase에 적용',
    anatomyCooldown: 'SOVT 또는 가벼운 /m/',
    variableAxes: {
      'genreTone': [
        'gayo_clean',
        'musical_text_forward',
        'classical_legato',
        'rnb_warm',
        'rock_clean_edge',
      ],
      'phraseLength': ['10초', '20초'],
    },
    timbreTags: ['genreTone', 'advanced', 'portfolio'],
    timbreLayer: 'style',
    toneTagOptions: [
      'comfortable', 'clean', 'warm', 'bright', 'clear', 'speechLike', 'round', 'micFriendly',
    ],
    toneGoal: '고급 장르 Lab에서 참조 음색을 안전하게 적용한다.',
    allowsToneAB: true,
    requiresSameRecordingCondition: true,
    safetyIntensity: 'moderate',
    maxReps: 3,
    maxDurationSec: 120,
    maxTakeCount: 3,
    weeklyCap: 2,
    fallbackCardId: 'TONE-12',
  ),

  // ===== R4 Repertoire Application 카드 (RA, 곡 적용 훈련) =====
  'RA-01': Card(
    id: 'RA-01',
    cue: ['가사를 먼저 말하기.', '의미 단어에 표시.', '같은 리듬으로 다시 말하기.', '아직 멜로디 없음.'],
    voicedMicroWin: ['가사 말하기→리듬 말하기 3회'],
    anatomyEntry: '문장 읽기',
    anatomyMain: 'text rhythm preparation',
    anatomyCooldown: '느린 호흡',
    variableAxes: {'phraseLength': ['2마디', '4마디']},
  ),
  'RA-02': Card(
    id: 'RA-02',
    cue: ['한 음으로 가사를 말하듯 부르기.', '자음은 박자 앞에 작게.', '끝을 밀지 않기.'],
    voicedMicroWin: ['한 음 speech-to-song phrase 5회'],
    anatomyEntry: '가사 말하기',
    anatomyMain: 'one-note singing phrase',
    anatomyCooldown: '가벼운 /m/',
    variableAxes: {'tone': ['speech_like', 'clean']},
  ),
  'RA-03': Card(
    id: 'RA-03',
    cue: ['허밍으로 멜로디 모양.', '모음 /u/로 같은 모양.', '마지막에 짧은 가사.'],
    voicedMicroWin: ['hum→vowel→lyric phrase 3회'],
    anatomyEntry: 'melody contour 듣기',
    anatomyMain: 'melody transfer',
    anatomyCooldown: '하행 허밍',
    variableAxes: {'vowel': ['m', 'u', 'a'], 'phraseLength': ['2마디', '4마디']},
    deferredVisualFeedback: true,
  ),
  'RA-04': Card(
    id: 'RA-04',
    cue: ['호흡 표시를 보고 시작.', 'phrase 끝에서 밀지 않기.', '남기고 끝내기.'],
    voicedMicroWin: ['breath-mark phrase 4회'],
    anatomyEntry: '호흡 위치 확인',
    anatomyMain: 'phrase breath management',
    anatomyCooldown: '느린 날숨',
    variableAxes: {'length': ['4박', '6박', '8박']},
  ),
  'RA-05': Card(
    id: 'RA-05',
    cue: ['guide vocal을 듣기.', '혼자 한 번.', '끝난 뒤 비교.', '다시 1회만.'],
    voicedMicroWin: ['guide→solo→A/B 비교 2쌍'],
    anatomyEntry: 'guide vocal 듣기',
    anatomyMain: 'guided phrase imitation',
    anatomyCooldown: '가벼운 허밍',
    variableAxes: {'feedback': ['deferred', 'A/B']},
    allowsToneAB: true,
    requiresSameRecordingCondition: true,
  ),
  'RA-06': Card(
    id: 'RA-06',
    cue: ['반주에 맞춰 첫 음만 잡기.', '4박 안에서 시작.', '틀려도 작게 다시.'],
    voicedMicroWin: ['backing-track entry 5회'],
    anatomyEntry: '첫 음 듣기',
    anatomyMain: '반주 위 entry timing',
    anatomyCooldown: '느린 호흡',
    variableAxes: {'tempo': ['느림', '원템포 -20%']},
    deferredVisualFeedback: true,
  ),
  'RA-07': Card(
    id: 'RA-07',
    cue: ['어려운 2마디만 반복.', '느린 tempo로.', '원 tempo는 선택.', '3회까지만.'],
    voicedMicroWin: ['difficult phrase loop 최대 3회'],
    anatomyEntry: '어려운 구간 듣기',
    anatomyMain: 'slow loop practice',
    anatomyCooldown: 'SOVT 또는 /m/',
    variableAxes: {'tempo': ['slow', 'medium'], 'loop': ['2마디', '4마디']},
    safetyIntensity: 'moderate',
  ),
  'RA-08': Card(
    id: 'RA-08',
    cue: ['오늘의 best take 1개만 저장.', '다시 듣고 태그 선택.', '내일 바꿀 점 1개만.'],
    voicedMicroWin: ['portfolio take 저장 + 자기 태그'],
    anatomyEntry: 'take 준비',
    anatomyMain: 'one-take recording review',
    anatomyCooldown: '가벼운 쿨다운',
    variableAxes: {'review': ['bestTake', 'nextCue']},
    allowsToneAB: true,
    requiresSameRecordingCondition: true,
  ),

  'RA-09': Card(
    id: 'RA-09',
    cue: [
      '전체 2–8마디를 먼저 듣기.',
      '오늘의 목표 하나만 표시.',
      '중간에 멈추지 않고 낮은 부하로 한 번.',
      '교정은 끝난 뒤.',
    ],
    voicedMicroWin: ['전체 phrase baseline take 1회'],
    anatomyEntry: '전체 phrase 듣기',
    anatomyMain: 'Global Phrase Baseline',
    anatomyCooldown: '느린 호흡과 짧은 메모',
    variableAxes: {
      'phraseLength': ['2마디', '4마디', '8마디'],
      'primaryGoal': ['pitch', 'rhythm', 'breath', 'tone', 'diction'],
    },
    allowsToneAB: true,
    requiresSameRecordingCondition: true,
    maxTakeCount: 1,
  ),
  'RA-10': Card(
    id: 'RA-10',
    cue: [
      '가이드 없이 전체 phrase 한 번.',
      '첫날 take와 비교.',
      '다른 key·tempo·문구 중 하나만 바꾸기.',
      'best take와 다음 cue 하나 저장.',
    ],
    voicedMicroWin: ['지연 재현→한 조건 전이→프로젝트 리뷰'],
    anatomyEntry: '가이드 없는 준비',
    anatomyMain: 'Delayed Retrieval & Project Review',
    anatomyCooldown: '회복 루틴 또는 듣기-only 리뷰',
    variableAxes: {
      'transfer': ['key', 'tempo', 'lyric', 'tone'],
      'review': ['baselineCompare', 'bestTake', 'nextCue'],
    },
    allowsToneAB: true,
    requiresSameRecordingCondition: true,
    maxTakeCount: 2,
  ),

  // ===== R5g 곡 적용 확장 카드(RA-11~28) — 리서치 영역 심화 =====
  // 초반(프로젝트 1~2): 프레이즈 안착
  'RA-11': Card(
    id: 'RA-11',
    cue: [
      '오늘의 SOVT/모음 vocalise 5회.',
      '같은 조절이 필요한 새 verse 2마디를 허밍으로.',
      '같은 2마디를 모음으로 옮기기.',
      '연습이 어느 박에서 깨졌는지 한 곳만 표시.',
    ],
    voicedMicroWin: ['vocalise→verse 2마디 전이 1세트'],
    anatomyEntry: '모음 vocalise',
    anatomyMain: 'Vocalise→Verse 전이',
    anatomyCooldown: '하행 허밍',
    maxSustainSec: 4,
  ),
  'RA-12': Card(
    id: 'RA-12',
    cue: [
      '4마디 verse를 2+2 호흡 단위로 나누기.',
      '앞 2마디 먼저 편하게.',
      '뒤 2마디 따로.',
      '두 단위를 호흡 위치만 지키며 잇기.',
    ],
    voicedMicroWin: ['2+2 sub-phrase 체이닝 완주'],
    anatomyEntry: '호흡 단위 나누기',
    anatomyMain: 'Sub-Phrase Chaining',
    anatomyCooldown: '느린 날숨',
    maxSustainSec: 6,
  ),
  'RA-13': Card(
    id: 'RA-13',
    cue: [
      '가사를 자연스럽게 말하기.',
      '클릭에 맞춰 리듬으로 말하기.',
      '한 음으로 챈트.',
      '가장 약했던 한 단계만 한 번 더.',
    ],
    voicedMicroWin: ['speak→rhythm speak→chant 3단 전이'],
    anatomyEntry: '가사 말하기',
    anatomyMain: 'Speak→Chant 분해',
    anatomyCooldown: '가벼운 /m/',
    maxSustainSec: 3,
  ),
  'RA-14': Card(
    id: 'RA-14',
    cue: [
      '짧은 2마디 motif를 편한 모음으로.',
      '같은 모양을 아-에-이-오-우로 차례로.',
      '가장 흔들린 모음 한 번 더 안착.',
      '턱을 크게 움직이지 않기.',
    ],
    voicedMicroWin: ['한 contour의 5모음 안정 1세트'],
    anatomyEntry: '편한 모음 motif',
    anatomyMain: 'Vowel Ladder on Phrase',
    anatomyCooldown: '하행 허밍',
    maxSustainSec: 4,
  ),
  // 중반(프로젝트 3~4): 구간 연결·반주 의존도 축소
  'RA-15': Card(
    id: 'RA-15',
    cue: [
      'verse 마지막 마디만.',
      'chorus 첫 마디만.',
      '두 구간을 이음새 호흡 한 번으로 잇기.',
      '이음새에서 음량 밀지 않기.',
    ],
    voicedMicroWin: ['verse→chorus 이음새 연결 3회'],
    anatomyEntry: '구간 끝/시작 확인',
    anatomyMain: 'Verse→Chorus 이음새',
    anatomyCooldown: '하행 허밍',
    maxSustainSec: 6,
    safetyIntensity: 'moderate',
  ),
  'RA-16': Card(
    id: 'RA-16',
    cue: [
      'full backing으로 4마디 1회.',
      'sparse(피아노/패드) 반주로 같은 4마디.',
      '두 반주에서 달라진 한 곳만 표시.',
      '어려우면 full로 한 번 복귀.',
    ],
    voicedMicroWin: ['full→sparse 반주 1단계 축소 통과'],
    anatomyEntry: 'full backing',
    anatomyMain: '반주 축소 (full→sparse)',
    anatomyCooldown: '하행 허밍',
    maxSustainSec: 6,
    safetyIntensity: 'moderate',
  ),
  'RA-17': Card(
    id: 'RA-17',
    cue: [
      '피아노 가이드로 첫 음 확인.',
      'count-in을 끝까지 듣기.',
      '가이드 끄고 independent backing으로 첫 마디 작게.',
      '첫 음 정확도와 박 진입을 따로 확인.',
    ],
    voicedMicroWin: ['가이드 off 첫 음 자력 진입 3회'],
    anatomyEntry: '가이드 첫 음',
    anatomyMain: 'Guide Fade Entry',
    anatomyCooldown: '가벼운 /m/',
    maxSustainSec: 4,
    safetyIntensity: 'moderate',
  ),
  'RA-18': Card(
    id: 'RA-18',
    cue: [
      'sparse backing으로 4마디.',
      'count-in만 듣고 a cappella로 같은 4마디.',
      '끝 음이 시작 기준에서 벗어났는지 듣기.',
      '드리프트 크면 sparse로 복귀.',
    ],
    voicedMicroWin: ['sparse→a cappella 드리프트 점검 1세트'],
    anatomyEntry: 'sparse backing',
    anatomyMain: '반주 축소 (sparse→a cappella)',
    anatomyCooldown: '하행 허밍',
    maxSustainSec: 6,
    safetyIntensity: 'moderate',
  ),
  'RA-19': Card(
    id: 'RA-19',
    cue: [
      '편한 반주 음량에서 4마디.',
      '반주 조금 키운 뒤 같은 편안함으로.',
      '끝나면 노력도 0–10 적기.',
      '노력도 오르면 반주 줄여 다시.',
    ],
    voicedMicroWin: ['두 반주 음량에서 노력도 ≤3 유지'],
    anatomyEntry: '편한 반주 음량',
    anatomyMain: 'Backing Volume Calibration',
    anatomyCooldown: '느린 호흡 3회',
    maxSustainSec: 6,
    safetyIntensity: 'moderate',
  ),
  // 후반(프로젝트 5~6): 전이·표현 입문·한국어 딕션·산출물
  'RA-20': Card(
    id: 'RA-20',
    cue: [
      '익숙한 프레이즈 한 번.',
      '같은 난이도 처음 보는 프레이즈를 scaffold 최소로.',
      '어느 요소가 옮겨졌고 어디서 깨졌는지 한 줄.',
      '세 번 이내로 통과 시도.',
    ],
    voicedMicroWin: ['unseen 프레이즈 3회 이내 통과 산출물'],
    anatomyEntry: '익숙한 프레이즈',
    anatomyMain: 'Unseen Phrase Transfer',
    anatomyCooldown: '하행 허밍',
    maxSustainSec: 6,
    safetyIntensity: 'moderate',
  ),
  'RA-21': Card(
    id: 'RA-21',
    cue: [
      '기준 템포(100%)로 4마디.',
      '90% 또는 110% 템포로 같은 프레이즈.',
      '가사 누락·박 밀림 생긴 한 곳만 표시.',
      '안정되면 산출물로 남기기.',
    ],
    voicedMicroWin: ['±10% 템포 전이 1조건 통과'],
    anatomyEntry: '기준 템포',
    anatomyMain: 'New-Tempo Transfer',
    anatomyCooldown: '느린 호흡 3회',
    maxSustainSec: 6,
    safetyIntensity: 'moderate',
  ),
  'RA-22': Card(
    id: 'RA-22',
    cue: [
      '4마디를 중립으로 한 번.',
      '핵심 단어 하나 정하고 의도를 말로.',
      '음량보다 프레이즈 모양(앞 강조/끝 정리)으로 같은 4마디.',
      '두 버전 의도 차이가 들리는지 자기평가.',
    ],
    voicedMicroWin: ['같은 음형 2의도 표현 대비 1세트'],
    anatomyEntry: '중립 버전',
    anatomyMain: '표현 입문 (의도 2종)',
    anatomyCooldown: '하행 허밍',
    maxSustainSec: 5,
  ),
  'RA-23': Card(
    id: 'RA-23',
    cue: [
      'verse 끝~chorus 전 구간을 작게 시작.',
      '한 마디마다 아주 조금씩만 키우기.',
      'peak 직전 노력도 확인.',
      '노력도 오르면 build 폭 줄여 다시.',
    ],
    voicedMicroWin: ['점진 build, peak 전 노력도 ≤3'],
    anatomyEntry: '작게 시작',
    anatomyMain: 'Gradual Dynamic Build',
    anatomyCooldown: '하행 허밍',
    maxSustainSec: 6,
    safetyIntensity: 'moderate',
  ),
  'RA-24': Card(
    id: 'RA-24',
    cue: [
      '받침 있는 가사 구절 말하기.',
      '음 길이 앞 8~9할은 모음 유지.',
      '정지음 종성(ㄱ·ㄷ·ㅂ)은 마지막에 짧은 폐쇄로만, 터뜨리지 않기.',
      '비음·유음 종성(ㄴ·ㅁ·ㅇ·ㄹ)은 끝 10%만 sustain.',
    ],
    voicedMicroWin: ['종성 늦게·짧게 닫기 5회'],
    anatomyEntry: '받침 구절',
    anatomyMain: '한국어 종성 가사 처리',
    anatomyCooldown: '입 다문 허밍',
    maxSustainSec: 3,
  ),
  'RA-25': Card(
    id: 'RA-25',
    cue: [
      '가사를 발음형으로 전사(예: 꽃이→꼬치).',
      '이동하는 자음을 다음 음표 직전에.',
      '반주에 맞춰 두 마디를 연음 적용해.',
      '표기 음절 단위로 끊지 않기.',
    ],
    voicedMicroWin: ['연음 적용 legato 구간 3회'],
    anatomyEntry: '발음형 전사',
    anatomyMain: '한국어 연음 legato',
    anatomyCooldown: '하행 허밍',
    maxSustainSec: 4,
  ),
  'RA-26': Card(
    id: 'RA-26',
    cue: [
      '같은 마이크·거리·반주 조건 고정.',
      '사전 연습 최소로 backing-only 1회 녹음.',
      '지난 take와 주 목표 하나로 비교.',
      '하락 허용폭 안인지, 다음 cue 하나 기록.',
    ],
    voicedMicroWin: ['동일 조건 지연 재현 비교 산출물'],
    anatomyEntry: '표준 녹음 조건',
    anatomyMain: 'Delayed Retake (24–48h)',
    anatomyCooldown: '듣기-only 리뷰',
    maxSustainSec: 6,
    requiredRestHours: 24,
    safetyIntensity: 'moderate',
  ),
  'RA-27': Card(
    id: 'RA-27',
    cue: [
      '듣기 전 예상 오류를 pitch/rhythm/lyric/breath 중 하나로 먼저.',
      '녹음 듣고 실제 1순위 문제 고르기.',
      '둘이 같은 범주인지 확인.',
      '어긋나면 그 구간만 다시 듣기.',
    ],
    voicedMicroWin: ['자기평가↔실제 오류 범주 일치 1세트'],
    anatomyEntry: '예상 오류 선택',
    anatomyMain: 'Self-Review Calibration',
    anatomyCooldown: '짧은 자기평가',
    maxSustainSec: 4,
  ),
  'RA-28': Card(
    id: 'RA-28',
    cue: [
      '첫 곡 조각에서 목표 기술을 backing-only로 1회.',
      '다른 곡(다른 key/tempo) 조각에서 같은 기술 1회.',
      '두 곡에서 기술 유지됐는지 자기평가.',
      '더 편한 take 두 개 저장.',
    ],
    voicedMicroWin: ['서로 다른 2곡 같은 기술 산출물'],
    anatomyEntry: '첫 곡 조각',
    anatomyMain: 'Module Pass (2곡 전이)',
    anatomyCooldown: '회복 루틴',
    maxSustainSec: 6,
    safetyIntensity: 'moderate',
  ),

  // ===== 중급 코어 (intermediate-core, IC) =====
  'IC-01': Card(
    id: 'IC-01',
    cue: ['짜내지도 새지도 않게.', '그 사이 편한 지점에서 5초.', '화면 곡선으로 확인.'],
    voicedMicroWin: ['균형 지점 sustain 5초 × 4'],
    anatomyEntry: '가벼운 onset',
    anatomyMain: '과기식↔균형↔과압착 탐색',
    anatomyCooldown: '가벼운 허밍',
    variableAxes: {
      'range': ['중음', '±2도'],
      'vowel': ['a', 'i', 'u'],
    },
  ),
  'IC-02': Card(
    id: 'IC-02',
    cue: ['빨대로 /u/ 또는 립 트릴 5초.', '이로 물지 마세요.', '일정한 굵기 유지.', '어지러우면 즉시 멈추세요.'],
    voicedMicroWin: ['SOVT sustain 5초 × 3'],
    anatomyEntry: '무음 호기 1회',
    anatomyMain: 'SOVT sustain·가벼운 글라이드',
    anatomyCooldown: '빨대 빼고 /u/ 1회',
    variableAxes: {
      'range': ['중음', '±3도'],
      'glide': ['sustain', '작은 글라이드'],
    },
  ),
  'IC-03': Card(
    id: 'IC-03',
    cue: ['① 가장 편한 음 최대한 길게.', '② /o/로 저→고 부드럽게.', '③ 고→저 부드럽게.', '④ 음별 최대 지속 — 짜내지 않게.'],
    voicedMicroWin: ['VFE 4과제 각 1회(저충격)'],
    anatomyEntry: '편한 음 1회',
    anatomyMain: 'knoll→글라이드→지속 4과제',
    anatomyCooldown: '가벼운 /m/',
    variableAxes: {
      'range': ['편한 중음', '약간 확장'],
    },
  ),
  'IC-04': Card(
    id: 'IC-04',
    cue: ['/h/로 숨 흘려보내듯 시작.', '/h/에 가볍게 소리 얹기.', '치지 말고 — 균형 onset이 유일 정답은 아님(편하게 탐색).'],
    voicedMicroWin: ['easy onset 5회'],
    anatomyEntry: '무성 호기 3회',
    anatomyMain: 'hard/balanced/breathy 대조',
    anatomyCooldown: '가벼운 /m/ 하행',
    variableAxes: {
      'onset': ['balanced', 'breathy'],
      'range': ['중음'],
    },
  ),
  'IC-05': Card(
    id: 'IC-05',
    cue: ['들숨 자세(흉곽 확장)를 노래하는 동안 유지.', '내쉴 때 한꺼번에 무너뜨리지 않기.'],
    voicedMicroWin: ['흡기자세 유지 발성 5초 × 3'],
    anatomyEntry: '늑골 확장 인지',
    anatomyMain: '흡기자세 유지 호기 antagonism',
    anatomyCooldown: '느린 날숨 연장',
    variableAxes: {
      'range': ['중음', '±2도'],
    },
  ),
  'IC-06': Card(
    id: 'IC-06',
    cue: ['빨대 /u/ 5초.', '빨대 빼고 같은 음 개모음(/a/)으로 이어가기.', '느낌 유지(carryover).'],
    voicedMicroWin: ['SOVT→개모음 carryover 5회'],
    anatomyEntry: '빨대 /u/ 1회',
    anatomyMain: 'SOVT→개모음 전이 반복',
    anatomyCooldown: '가벼운 허밍',
    variableAxes: {
      'vowel': ['a', 'o', 'e'],
      'range': ['중음', '±2도'],
    },
  ),
  'IC-07': Card(
    id: 'IC-07',
    cue: ['같은 음에서 모음을 /i/↔/a/↔/u/로 천천히 바꾸기.', '밝기·울림 변화를 화면으로 관찰.', '(고소프라노 조정·belt 방향은 여기서 안 함).'],
    voicedMicroWin: ['모음 전환 sustain 5회'],
    anatomyEntry: '편한 음 1회',
    anatomyMain: 'R1:f0 관계 기초 관찰',
    anatomyCooldown: '하행 글라이드',
    variableAxes: {
      'vowel': ['i', 'a', 'u'],
      'range': ['중음', '±2도'],
    },
  ),
  'IC-08': Card(
    id: 'IC-08',
    cue: ['같은 문장을 또렷하게 vs 편하게 두 번.', '차이를 화면·감각으로 관찰.', '정답은 장르·증폭에 따라 다름 — 지금은 관찰만.'],
    voicedMicroWin: ['명료/효율 대조 발성 각 3회'],
    anatomyEntry: '편한 발성',
    anatomyMain: '명료도↔효율 대조 관찰',
    anatomyCooldown: '가벼운 허밍',
    variableAxes: {
      'sessionPos': ['워밍업', '본'],
    },
  ),
  'IC-09': Card(
    id: 'IC-09',
    cue: ['삼킬 때(후두↑)와 하품 시작(후두↓) 느낌 비교.', '노래는 그 사이 편한 높이.', '(클래식 저·CCM 고 타깃은 분기에서).'],
    voicedMicroWin: ['중립 후두높이 sustain 5초 × 3'],
    anatomyEntry: '후두 높이 인지',
    anatomyMain: '중립 높이 통제변수 관찰',
    anatomyCooldown: '느린 호흡',
    variableAxes: {
      'range': ['중음'],
    },
  ),
  'IC-10': Card(
    id: 'IC-10',
    cue: ['/m/ 후 /a/로 — 비음이 빠지는지 관찰.', '트웽 = 입 안 좁힘(밝게), 콧소리 ❌.', '의도 nasality와 비의도 nasalization 구분.'],
    voicedMicroWin: ['/m/→/a/ 비음 분리 5회'],
    anatomyEntry: '가벼운 /m/',
    anatomyMain: '비음 ↔ 비비음 대조',
    anatomyCooldown: '가벼운 허밍',
    variableAxes: {
      'vowel': ['m', 'a', 'i'],
      'range': ['중음'],
    },
  ),
  'IC-11': Card(
    id: 'IC-11',
    cue: ['저음→고음 사이렌으로 천천히.', '소리 질감이 바뀌는 구간을 관찰(없애려 하지 않기).', '(믹스·belt·cover 처리는 분기에서).'],
    voicedMicroWin: ['사이렌 글라이드 3회'],
    anatomyEntry: '가벼운 글라이드',
    anatomyMain: 'primo/secondo passaggio 존재·관찰',
    anatomyCooldown: '하행 사이렌 1회',
    variableAxes: {
      'range': ['중음', '±3도', '약간 확장'],
      'glide': ['사이렌', '작은 글라이드'],
    },
  ),
  'IC-12': Card(
    id: 'IC-12',
    cue: ['조용한 곳에서 같은 조건으로.', '/a/ /i/ /u/ 각 5초 + 표준 문장 1줄 + 저→고→저 글라이드.', '녹음 후 시각 곡선을 직전 회차와 비교(듣고 판단 ❌).'],
    voicedMicroWin: ['고정 과제 녹음 1세트(전체 유성)'],
    anatomyEntry: '환경·자세 확인',
    anatomyMain: '고정 과제 녹음→직전 회차 시각 A/B',
    anatomyCooldown: '가벼운 허밍',
  ),

  // ===== 고급 뮤지컬 Lab 초안 (advanced-musical, IM) =====
  'IM-01': Card(
    id: 'IM-01',
    cue: ['이 음에서 이 느낌으로(흉성/두성 비율 설명 없이).', '저→고 한 호흡으로 부드럽게.', '갑자기 두꺼워지거나 얇아지지 않게.'],
    voicedMicroWin: ['믹스 글라이드 5회'],
    anatomyEntry: '가벼운 사이렌',
    anatomyMain: 'M1↔M2 연결(경험으로)',
    anatomyCooldown: '하행 글라이드',
    variableAxes: {
      'range': ['중음', '±3도'],
      'style': ['M1기반', 'M2기반'],
    },
  ),
  'IM-02': Card(
    id: 'IM-02',
    cue: ['오리·마녀 소리처럼 입 안을 좁혀 밝게.', '콧소리 ❌(트웽 = 입 안, 비음 아님).', '짧게 시작.'],
    voicedMicroWin: ['구강 트웽 발성 5회'],
    anatomyEntry: '가벼운 /a/',
    anatomyMain: '구강 AES 협착(밝게)',
    anatomyCooldown: '중립 모음 1회',
    variableAxes: {
      'vowel': ['a', 'e'],
      'range': ['중음'],
    },
    safetyReview: SafetyReview.pending,
    fallbackCardId: 'TONE-07',
    safetyIntensity: 'gated',
    maxReps: 3,
    maxDurationSec: 180,
    maxTakeCount: 2,
    maxSustainSec: 3,
    weeklyCap: 2,
    requiredRestHours: 24,
  ),
  'IM-03': Card(
    id: 'IM-03',
    cue: ['코어에서 관찰한 전이 구간을 사이렌으로 통과.', '없애려 하지 말고 부드럽게 관리.', '고음으로 밀어붙이지 않기.'],
    voicedMicroWin: ['전이 구간 사이렌 통과 5회'],
    anatomyEntry: '중음 사이렌',
    anatomyMain: 'primo/secondo 전이 관리',
    anatomyCooldown: '하행 사이렌',
    variableAxes: {
      'range': ['중음', '±4도'],
      'glide': ['사이렌', '작은 글라이드'],
    },
    safetyReview: SafetyReview.pending,
    fallbackCardId: 'UC-10',
    safetyIntensity: 'gated',
    maxReps: 3,
    maxDurationSec: 180,
    maxTakeCount: 2,
    maxSustainSec: 3,
    weeklyCap: 2,
    requiredRestHours: 24,
  ),
  'IM-04': Card(
    id: 'IM-04',
    cue: ['올라가며 모음을 살짝 어둡게 돌리기(turning the vowel).', '특정 음에서 울림이 바뀌는 지점 관찰.', '억지로 누르지 않기.'],
    voicedMicroWin: ['모음 전환 글라이드 5회'],
    anatomyEntry: '편한 모음 1회',
    anatomyMain: 'H2가 R1 통과 지점 모음 조정',
    anatomyCooldown: '가벼운 허밍',
    variableAxes: {
      'vowel': ['a→ɔ', 'e→ø'],
      'range': ['중고음'],
    },
  ),
  'IM-05': Card(
    id: 'IM-05',
    cue: ["'Hey!' 부르듯 짧게.", '밝게 — 크게 아님.', '짧게 끊어서, 지속하지 않기.', '조금이라도 아프면 즉시 멈춤.'],
    voicedMicroWin: ["call-based 'Hey!' 진입 3회(짧게)"],
    anatomyEntry: '가벼운 call',
    anatomyMain: 'call-based belt 진입만(보수적)',
    anatomyCooldown: '하행 글라이드·가벼운 SOVT',
    variableAxes: {
      'range': ['진입 음역 한정'],
    },
    safetyReview: SafetyReview.pending,
    fallbackCardId: 'GY-08',
    safetyIntensity: 'gated',
    maxReps: 3,
    maxDurationSec: 180,
    maxTakeCount: 2,
    maxSustainSec: 3,
    weeklyCap: 2,
    requiredRestHours: 24,
  ),
  'IM-06': Card(
    id: 'IM-06',
    cue: ['문장을 보통/뭉갬/정밀 3가지로.', '정밀 버전 채택.', '말하듯(chant) → 노래로 이어가기.'],
    voicedMicroWin: ['chant→sing 전이 3회'],
    anatomyEntry: '문장 말하기',
    anatomyMain: '3조건 대조→정밀 채택→chant→sing',
    anatomyCooldown: '가벼운 허밍',
    variableAxes: {
      'sessionPos': ['워밍업', '본'],
    },
  ),
  'IM-07': Card(
    id: 'IM-07',
    cue: ['테크닉 1분 미만.', '새 호흡.', '텍스트를 말로 전달.', '같은 텍스트를 음정과 함께.', '3회 반복.'],
    voicedMicroWin: ['텍스트 말→노래 루프 3회'],
    anatomyEntry: '짧은 테크닉',
    anatomyMain: '말 전달→음정 전달 루프',
    anatomyCooldown: '느린 호흡',
    variableAxes: {
      'sessionPos': ['본'],
    },
  ),
  'IM-08': Card(
    id: 'IM-08',
    cue: ['녹음 후 가사가 또렷한지 화면·구조로 확인.', '듣고 판단하지 말고 시각/체크로.'],
    voicedMicroWin: ['명료도 점검 발성 3회'],
    anatomyEntry: '문장 1회',
    anatomyMain: '명료도 시각/구조 피드백',
    anatomyCooldown: '가벼운 허밍',
    variableAxes: {
      'sessionPos': ['본'],
    },
  ),
  'IM-09': Card(
    id: 'IM-09',
    cue: ['평·경·격음 구분 — 경음은 과압 주의(짜내지 않기).', '종성 7대표음 또렷이.', '연음·비음화 자연스럽게.', '곡과 함께(고립 ❌).'],
    voicedMicroWin: ['딕션 적용 구절 3회'],
    anatomyEntry: '문장 말하기',
    anatomyMain: 'VOT·종성·연음 적용(곡 안)',
    anatomyCooldown: '가벼운 허밍',
    variableAxes: {
      'sessionPos': ['본'],
    },
  ),
  'IM-10': Card(
    id: 'IM-10',
    cue: ['짧은 구절을 느리게 → 점점 빠르게.', '또렷함 유지되는 최대 템포까지만.', '무너지면 한 단계 늦춤.'],
    voicedMicroWin: ['패터 템포 램프 3단계'],
    anatomyEntry: '느린 구절',
    anatomyMain: '조음 템포 램프',
    anatomyCooldown: '턱 풀기',
    variableAxes: {
      'tempo': ['느림', '중간', '빠름'],
    },
  ),
  'IM-11': Card(
    id: 'IM-11',
    cue: ['이중모음은 첫 모음 길게·끝 모음 짧게.', 'r은 곡 스타일대로(미·영).', '또렷하되 과하지 않게.'],
    voicedMicroWin: ['영어 구절 딕션 3회'],
    anatomyEntry: '구절 말하기',
    anatomyMain: '이중모음/r 정책 적용',
    anatomyCooldown: '가벼운 허밍',
    variableAxes: {
      'sessionPos': ['본'],
    },
  ),
  'IM-12': Card(
    id: 'IM-12',
    cue: ['legit 구절은 맑게.', 'belt-진입 구절은 짧고 밝게(크게 아님).', '풀 벨트로 끌지 않기(고급).'],
    voicedMicroWin: ['곡 구절 적용 1회(legit 또는 라이트 belt-진입)'],
    anatomyEntry: '테크닉 1분',
    anatomyMain: 'legit→라이트 belt-진입 구절',
    anatomyCooldown: '하행 글라이드·SOVT',
    variableAxes: {
      'difficulty': ['legit', '라이트 belt-진입'],
    },
    safetyReview: SafetyReview.pending,
    fallbackCardId: 'IM-07',
    safetyIntensity: 'gated',
    maxReps: 3,
    maxDurationSec: 180,
    maxTakeCount: 2,
    maxSustainSec: 3,
    weeklyCap: 1,
    requiredRestHours: 24,
  ),

  // ===== 고급 성악 Lab 초안 (advanced-classical, CL) =====
  'CL-01': Card(
    id: 'CL-01',
    cue: ['올라가며 모음을 살짝 어둡게·둥글게.', '후두 누르기 ❌(모음·공간 조정만).', '진입까지만 — 고음 무리하지 않기.'],
    voicedMicroWin: ['cover 진입 글라이드 5회'],
    anatomyEntry: '중음 사이렌',
    anatomyMain: '패사지오 위 모음 둥글게(진입)',
    anatomyCooldown: '하행 사이렌·SOVT',
    variableAxes: {
      'range': ['중고음(진입 한정)'],
      'glide': ['사이렌'],
    },
    safetyReview: SafetyReview.pending,
    fallbackCardId: 'CL-02',
    safetyIntensity: 'gated',
    maxReps: 3,
    maxDurationSec: 180,
    maxTakeCount: 2,
    maxSustainSec: 3,
    weeklyCap: 2,
    requiredRestHours: 24,
  ),
  'CL-02': Card(
    id: 'CL-02',
    cue: ['올라갈수록 /a/를 /ɔ/ 쪽으로 살짝.', '모음 고정한 채 비명 ❌.', '저음에선 과한 조정 ❌.'],
    voicedMicroWin: ['모음 조정 글라이드 5회'],
    anatomyEntry: '편한 모음 1회',
    anatomyMain: 'f0 상승 시 모음 중립화',
    anatomyCooldown: '하행 글라이드',
    variableAxes: {
      'vowel': ['a→ɔ', 'e→ø'],
      'range': ['중고음'],
    },
  ),
  'CL-03': Card(
    id: 'CL-03',
    cue: ['밝되 먹먹하지 않게.', '둥글되 날카롭지 않게.', '두 느낌을 동시에.'],
    voicedMicroWin: ['chiaroscuro 균형 sustain 5초 × 3'],
    anatomyEntry: '편한 음 1회',
    anatomyMain: 'ring+공간 동시 균형 탐색',
    anatomyCooldown: '가벼운 허밍',
    variableAxes: {
      'vowel': ['a', 'o', 'e'],
      'range': ['중음', '±2도'],
    },
  ),
  'CL-04': Card(
    id: 'CL-04',
    cue: ['울림이 모이는 지점을 화면으로 관찰.', '2.8–3.2kHz ring 맛보기.', 'placement(어디에 둔다) 식 은유 ❌.'],
    voicedMicroWin: ['ring 인지 sustain 5초 × 3'],
    anatomyEntry: '편한 음 1회',
    anatomyMain: "singer's formant 인지·맛보기",
    anatomyCooldown: '가벼운 허밍',
    variableAxes: {
      'range': ['중음', '±2도'],
    },
  ),
  'CL-05': Card(
    id: 'CL-05',
    cue: ['음과 음 사이 끊김 없이.', '자음으로 라인 끊지 않기.', '한 호흡 안에서 흐르게.'],
    voicedMicroWin: ['legato 라인 구절 3회'],
    anatomyEntry: '5음 글라이드',
    anatomyMain: '끊김 없는 라인(자음 흐름)',
    anatomyCooldown: '하행 글라이드',
    variableAxes: {
      'range': ['중음', '±3도'],
    },
  ),
  'CL-06': Card(
    id: 'CL-06',
    cue: ['순수 5모음(a·e·i·o·u) 또렷이.', '이중자음 길게.', '곡과 함께(고립 ❌).'],
    voicedMicroWin: ['이탈리아어 구절 딕션 3회'],
    anatomyEntry: '모음 말하기',
    anatomyMain: '순수모음·이중자음 적용(곡 안)',
    anatomyCooldown: '가벼운 허밍',
    variableAxes: {
      'sessionPos': ['본'],
    },
  ),
  'CL-07': Card(
    id: 'CL-07',
    cue: ['움라우트(ü·ö) 입모양 정확히.', '자음군·종성 또렷이.', '곡과 함께.'],
    voicedMicroWin: ['독일어 구절 딕션 3회'],
    anatomyEntry: '모음 말하기',
    anatomyMain: '움라우트·자음군 적용(곡 안)',
    anatomyCooldown: '가벼운 허밍',
    variableAxes: {
      'sessionPos': ['본'],
    },
  ),
  'CL-08': Card(
    id: 'CL-08',
    cue: ['한 음에서 천천히 부풀렸다(약→강) 줄이기(강→약).', '기초만 — 무리한 강세 ❌.', '편한 중음역에서.'],
    voicedMicroWin: ['messa di voce 기초 곡선 3회'],
    anatomyEntry: '편한 음 sustain',
    anatomyMain: '약→강→약 다이내믹 기초',
    anatomyCooldown: '가벼운 허밍',
    variableAxes: {
      'range': ['편한 중음(기초 한정)'],
    },
    safetyReview: SafetyReview.pending,
    fallbackCardId: 'TONE-08',
    safetyIntensity: 'gated',
    maxReps: 3,
    maxDurationSec: 180,
    maxTakeCount: 2,
    maxSustainSec: 3,
    weeklyCap: 2,
    requiredRestHours: 24,
  ),
  'CL-09': Card(
    id: 'CL-09',
    cue: ['legit 클래식 구절 맑게·둥글게.', 'legato 유지.', '풀 covered 고음·풀 messa 구절 ❌(고급).'],
    voicedMicroWin: ['아리아/리트 구절 적용 1회'],
    anatomyEntry: '테크닉 1분',
    anatomyMain: 'legit 클래식 구절 적용',
    anatomyCooldown: '하행 글라이드·SOVT',
    variableAxes: {
      'difficulty': ['리트 구절', '쉬운 아리아 구절'],
    },
  ),

  // ===== R5h 고급 안전 카드(리서치 근거, 게이팅 불필요) =====
  // 성악: cover/squillo/full messa 전 단계의 저위험 on-ramp
  'CL-10': Card(
    id: 'CL-10',
    cue: [
      '립트릴/빨대로 편한 음에서 상행 글라이드.',
      '성도 모양을 고정한 채 전이가 저절로 넘어가게.',
      '같은 글라이드를 /i/·/e/·/a/로.',
      '목 누르거나 혀뿌리 내리지 않기(둔탁+커짐 신호면 중단).',
    ],
    voicedMicroWin: ['수동 모음변형 글라이드 5회'],
    anatomyEntry: 'SOVT 글라이드',
    anatomyMain: '수동 모음변형 (passive)',
    anatomyCooldown: '하행 글라이드',
    maxSustainSec: 6,
    safetyIntensity: 'moderate',
  ),
  'CL-11': Card(
    id: 'CL-11',
    cue: [
      '지속음에서 아주 천천히 작게→조금 크게→작게.',
      '음정이 흔들리거나 튀지 않게(F0 유지).',
      '여린 끝(pianissimo)에서 레지스터 뒤집힘 없게.',
      '노력 급증·통증이면 중단. full 메사 전 준비 단계.',
    ],
    voicedMicroWin: ['pre-messa 스웰 안정 3회'],
    anatomyEntry: '균형 온셋',
    anatomyMain: 'Pre-Messa 스웰 준비',
    anatomyCooldown: '느린 날숨',
    maxSustainSec: 8,
    safetyIntensity: 'moderate',
  ),
  'CL-12': Card(
    id: 'CL-12',
    cue: [
      '내 패사지오 근처 음에서 /i/를 부르기.',
      '상행하며 /i/→/ɪ/→/e/ 방향으로 아주 조금씩.',
      '강제로 둥글리지 말고 가장 편한 색을 찾기.',
      '딕션이 무너지면 수정폭 줄이기.',
    ],
    voicedMicroWin: ['모음 사다리 인지 1세트'],
    anatomyEntry: '패사지오 음',
    anatomyMain: 'Aggiustamento 인지 사다리',
    anatomyCooldown: '하행 허밍',
    maxSustainSec: 4,
  ),
  // 뮤지컬: belt 진입이 아니라 climax 디에스컬레이션·부하 관리
  'IM-13': Card(
    id: 'IM-13',
    cue: [
      'climax 음을 belt 대신 mix/legit로 같은 음정 유지.',
      '음량 한 단계 낮추되 음정은 그대로(F0 유지).',
      '목 압박 늘면 즉시 더 가볍게.',
      '세 버전(mix/legit/말하듯) 중 가장 편한 걸 고르기.',
    ],
    voicedMicroWin: ['climax belt→대안 전환 3회'],
    anatomyEntry: 'climax 음 확인',
    anatomyMain: 'Belt→Mix 디에스컬레이션',
    anatomyCooldown: '하행 허밍',
    maxSustainSec: 4,
    safetyIntensity: 'moderate',
  ),
  'IM-14': Card(
    id: 'IM-14',
    cue: [
      '오늘 통증·쉰소리·피로·고음 상실을 체크.',
      '노래+대사+리허설+소음 속 대화를 합산 기록.',
      '증상 있으면 무발성/저강도로 전환.',
      '2~3주 이상 쉰소리면 전문가 안내.',
    ],
    voicedMicroWin: ['부하 로그 + 디로드 판단 1회'],
    anatomyEntry: '증상 체크인',
    anatomyMain: '부하 로그·디로드',
    anatomyCooldown: '느린 호흡 3회',
    maxDurationSec: 300,
  ),

  // ===== 고급 가요 Lab 초안 (advanced-gayo, GY) =====
  'GY-01': Card(
    id: 'GY-01',
    cue: ['말하듯 편한 위치에서 시작.', '그대로 노래로 이어가기.', '지르지 않기(마이크가 음량 보완).'],
    voicedMicroWin: ['말→노래 전이 5회'],
    anatomyEntry: '문장 말하기',
    anatomyMain: '말소리 위치→노래 carryover',
    anatomyCooldown: '가벼운 허밍',
    variableAxes: {
      'range': ['중음', '±2도'],
      'sessionPos': ['워밍업', '본'],
    },
  ),
  'GY-02': Card(
    id: 'GY-02',
    cue: ['이 음에서 이 느낌으로(비율 설명 없이).', '저→고 부드럽게.', '갑자기 두꺼워지거나 얇아지지 않게.'],
    voicedMicroWin: ['믹스 글라이드 5회'],
    anatomyEntry: '가벼운 사이렌',
    anatomyMain: 'M1↔M2 연결(경험으로)',
    anatomyCooldown: '하행 글라이드',
    variableAxes: {
      'range': ['중음', '±3도'],
      'style': ['M1기반', 'M2기반'],
    },
  ),
  'GY-03': Card(
    id: 'GY-03',
    cue: ['립버블(=립 트릴) 일정한 굵기로 5초.', '사이렌(글라이드) 저→고→저 부드럽게.', 'kkook = 짧고 단단하되 짜내지 않기(균형).'],
    voicedMicroWin: ['립버블·사이렌 각 3회'],
    anatomyEntry: '무음 호기 1회',
    anatomyMain: '산업명↔SOVT 워밍업(같은 운동)',
    anatomyCooldown: '빨대 빼고 /u/',
    variableAxes: {
      'range': ['중음', '±3도'],
      'glide': ['사이렌', 'sustain'],
    },
  ),
  'GY-04': Card(
    id: 'GY-04',
    cue: ['마녀 웃음·오리 소리처럼 입 안을 좁혀 밝게.', '콧소리 ❌(구강, 비음 아님).', '짧게 — 고음 지속 ❌.'],
    voicedMicroWin: ['구강 트웽 발성 5회'],
    anatomyEntry: '가벼운 /a/',
    anatomyMain: '구강 AES 협착(밝게)',
    anatomyCooldown: '중립 모음 1회',
    variableAxes: {
      'vowel': ['a', 'e'],
      'range': ['중음'],
    },
    safetyReview: SafetyReview.pending,
    fallbackCardId: 'TONE-07',
    safetyIntensity: 'gated',
    maxReps: 3,
    maxDurationSec: 180,
    maxTakeCount: 2,
    maxSustainSec: 3,
    weeklyCap: 2,
    requiredRestHours: 24,
  ),
  'GY-05': Card(
    id: 'GY-05',
    cue: ['부르듯 짧게(call-based).', '밝게 — 크게 아님.', '끊어서, 지속하지 않기.', '조금이라도 아프면 즉시 멈춤.'],
    voicedMicroWin: ['call-based 진입 3회(짧게)'],
    anatomyEntry: '가벼운 call',
    anatomyMain: '라이트 belt 진입만(보수적)',
    anatomyCooldown: '하행 글라이드·SOVT',
    variableAxes: {
      'range': ['진입 음역 한정'],
    },
    safetyReview: SafetyReview.pending,
    fallbackCardId: 'GY-08',
    safetyIntensity: 'gated',
    maxReps: 3,
    maxDurationSec: 180,
    maxTakeCount: 2,
    maxSustainSec: 3,
    weeklyCap: 2,
    requiredRestHours: 24,
  ),
  'GY-06': Card(
    id: 'GY-06',
    cue: ['음을 느리게 정확히 굴리기.', '정확도 먼저, 속도는 나중.', '고음역 무리 런 ❌.'],
    voicedMicroWin: ['느린 런 패턴 3회'],
    anatomyEntry: '느린 3음 패턴',
    anatomyMain: '런 기초 정확도→템포',
    anatomyCooldown: '가벼운 허밍',
    variableAxes: {
      'tempo': ['느림', '중간'],
      'range': ['중음'],
    },
    safetyReview: SafetyReview.pending,
    fallbackCardId: 'CARD-16',
    safetyIntensity: 'gated',
    maxReps: 3,
    maxDurationSec: 180,
    maxTakeCount: 2,
    maxSustainSec: 3,
    weeklyCap: 2,
    requiredRestHours: 24,
  ),
  'GY-07': Card(
    id: 'GY-07',
    cue: ['평·경·격음 구분 — 경음은 과압 주의(짜내지 않기).', '종성 7대표음 또렷이.', '연음·비음화 자연스럽게.', '곡과 함께(고립 ❌).'],
    voicedMicroWin: ['딕션 적용 구절 3회'],
    anatomyEntry: '문장 말하기',
    anatomyMain: 'VOT·종성·연음 적용(곡 안)',
    anatomyCooldown: '가벼운 허밍',
    variableAxes: {
      'sessionPos': ['본'],
    },
  ),
  'GY-08': Card(
    id: 'GY-08',
    cue: ['마이크가 음량 보완 — 과한 자음 타격 불필요.', '또렷하되 편하게.', '모니터·컴프레션 환경 인지.'],
    voicedMicroWin: ['증폭 전제 발성 3회'],
    anatomyEntry: '편한 발성',
    anatomyMain: '증폭 전제 명료도↔효율',
    anatomyCooldown: '가벼운 허밍',
    variableAxes: {
      'sessionPos': ['본'],
    },
  ),
  'GY-09': Card(
    id: 'GY-09',
    cue: ['스피치라이크 구절 편하게.', 'belt-진입 구절은 짧고 밝게(크게 ❌).', '풀 belt·고난도 런·고음 지속 구절 ❌(고급).'],
    voicedMicroWin: ['가요 구절 적용 1회(스피치라이크 또는 라이트 belt)'],
    anatomyEntry: '테크닉 1분',
    anatomyMain: '스피치라이크→라이트 belt 구절',
    anatomyCooldown: '하행 글라이드·SOVT',
    variableAxes: {
      'difficulty': ['스피치라이크', '라이트 belt-진입'],
    },
    safetyReview: SafetyReview.pending,
    fallbackCardId: 'GY-01',
    safetyIntensity: 'gated',
    maxReps: 3,
    maxDurationSec: 180,
    maxTakeCount: 2,
    maxSustainSec: 3,
    weeklyCap: 1,
    requiredRestHours: 24,
  ),
  // 가요 안전 딕션 보강 — ㄹ flap/lateral 가창 분배(저위험, 라이브러리 전용).
  // 근거: 표준 음운론(part 6-KR P6KR-03, B등급). 점수 없음·자기점검.
  'GY-10': Card(
    id: 'GY-10',
    cue: [
      '모음 사이 ㄹ("노래")은 아주 짧은 탭으로.',
      '종성·자음 앞 ㄹ("달·알다")은 끝 10~15%만 옆소리로 유지.',
      '두 ㄹ을 색으로 나눠 표시하고 곡과 함께.',
      '혀끝에 힘주거나 목 잠그지 않기.',
    ],
    voicedMicroWin: ['ㄹ 위치별 분배 구절 3회'],
    anatomyEntry: '구절 말하기',
    anatomyMain: '한국어 ㄹ flap/lateral 가창 분배',
    anatomyCooldown: '가벼운 허밍',
    timbreLayer: 'style',
    toneTagOptions: ['clear', 'clean', 'speechLike', 'soft'],
  ),
  // 가요 차별화 안전 카드(저위험, 라이브러리 전용). 무점수·폰 안전(타이밍/F0/자기보고).
  // 근거: 리듬 그루브 교수·KCI(이창구 2021)·세션 관행 B등급. 레이백 한 칸.
  'GY-11': Card(
    id: 'GY-11',
    cue: [
      '짧은 훅 한 구절을 먼저 정박에 맞춰.',
      '같은 글자를 박보다 아주 살짝 늦게 얹어.',
      '늦는 정도를 일정하게 유지.',
      '목에 힘주지 말고 리듬만 바꾸기.',
    ],
    voicedMicroWin: ['레이백 일정하게 얹기 3회'],
    anatomyEntry: '박 탭하기',
    anatomyMain: '온셋을 정박보다 살짝 뒤로(레이백)',
    anatomyCooldown: '느린 호흡 3회',
    timbreLayer: 'style',
    toneTagOptions: ['speechLike', 'comfortable'],
  ),
  // 근거: 그루브 교수·세션 관행 B등급. 당겨/밀어 싱코페이션 토글(타이밍만).
  'GY-12': Card(
    id: 'GY-12',
    cue: [
      '같은 훅을 정박으로 한 번.',
      '살짝 당겨서(앞으로) 한 번.',
      '살짝 밀어서(뒤로) 한 번.',
      '세 가지가 구분되게, 각자 일정하게.',
    ],
    voicedMicroWin: ['정박/당겨/밀어 3종 구분 1세트'],
    anatomyEntry: '박 탭하기',
    anatomyMain: '온셋 위치 토글(정박·당김·밀기)',
    anatomyCooldown: '느린 호흡 3회',
    timbreLayer: 'style',
    toneTagOptions: ['speechLike', 'comfortable'],
  ),
  // 근거: 꾸밈음의 음향 측정 B(방희석 2021)·국악 시김새 교수 B(박주만 2013).
  // ⚠️ 판소리 계보 주장 금지 — "한국 가요풍 꾸밈 제스처"로만(transfer 주장은 D).
  'GY-13': Card(
    id: 'GY-13',
    cue: [
      '편한 중간 음에서 한 모음을 길게.',
      '끝을 살짝 꺾어 내리거나 끌어올리기.',
      '음정 곡선의 모양만 따라가기(정확한 음 ❌).',
      '한국 가요풍 꾸밈 느낌으로 가볍게.',
    ],
    voicedMicroWin: ['방향 꾸밈(내림/올림) 곡선 3회'],
    anatomyEntry: '편한 음 1회',
    anatomyMain: '편한 음역 방향성 꾸밈(F0 곡선)',
    anatomyCooldown: '하행 허밍',
    relativePitchTarget: true,
    deferredVisualFeedback: true,
    timbreLayer: 'style',
    toneTagOptions: ['clear', 'soft', 'comfortable'],
  ),
  // 근거: 한국 녹음·보컬 가이드 수렴 B등급. 마이크 거리 다이내믹(부하 비의존).
  'GY-14': Card(
    id: 'GY-14',
    cue: [
      '센 부분은 마이크를 살짝 멀리.',
      '속삭이는 부분은 살짝 가까이.',
      '소리 크기는 거리로, 목 힘으로 ❌.',
      '구간마다 거리 변화를 체크.',
    ],
    voicedMicroWin: ['거리 다이내믹 적용 구절 3회'],
    anatomyEntry: '마이크 거리 확인',
    anatomyMain: '증폭 전제 거리 다이내믹(저부하)',
    anatomyCooldown: '가벼운 허밍',
    timbreLayer: 'style',
    toneTagOptions: ['comfortable', 'soft', 'clean'],
  ),
  // 근거: 곡 구조 자료 수렴 + 자기보고 C등급. 절→후렴 고조(부하 비증가).
  'GY-15': Card(
    id: 'GY-15',
    cue: [
      '절은 담담하게, 말하듯 담백하게.',
      '후렴은 마음을 여는 느낌으로 또렷하게.',
      '소리를 키우지 말고 표현·프레이징으로 고조.',
      '절→후렴에서 느낀 강도를 스스로 체크.',
    ],
    voicedMicroWin: ['절→후렴 고조 대비 구절 1회'],
    anatomyEntry: '구절 말하기',
    anatomyMain: '절→후렴 표현 고조(부하 비증가)',
    anatomyCooldown: '느린 호흡 3회',
    timbreLayer: 'style',
    toneTagOptions: ['speechLike', 'comfortable', 'clear'],
  ),
  // 근거: 싱잉랩이 가요/K-pop 정의 특징(C등급, 베타). 자동 판정 아님 — 안내만.
  'GY-16': Card(
    id: 'GY-16',
    cue: [
      '앞부분은 말하듯 좁은 음폭으로 리듬에 딱.',
      '마지막 단어만 음을 펴서 노래로.',
      '말→노래 전환점을 또렷이.',
      '리듬은 끝까지 박에 맞추기.',
    ],
    voicedMicroWin: ['말→노래 전이 구절 3회'],
    anatomyEntry: '리듬으로 말하기',
    anatomyMain: '랩싱잉 전이(좁은 음폭→펴기)',
    anatomyCooldown: '가벼운 허밍',
    timbreLayer: 'style',
    toneTagOptions: ['speechLike', 'comfortable', 'clear'],
  ),

  // ===== v9 Advanced R&B / Soul 저위험 전용 카드 =====
  'RB-01': Card(
    id: 'RB-01',
    cue: ['박자를 먼저 탭.', '가사를 리듬으로 말하기.', '한 음 허밍으로 groove 유지.', '크게 부르지 않기.'],
    voicedMicroWin: ['tap→speech→one-note groove 3세트'],
    anatomyEntry: 'groove 탭',
    anatomyMain: 'R&B Groove Skeleton',
    anatomyCooldown: '느린 탭과 호흡',
    variableAxes: {'groove': ['straight', 'light_swing'], 'tempo': ['slow', 'medium']},
  ),
  'RB-02': Card(
    id: 'RB-02',
    cue: ['같은 phrase를 박자 위에 한 번.', '조금 뒤에 놓는 느낌으로 한 번.', '반주를 놓치면 정박으로 돌아오기.', '둘 중 전달되는 take 선택.'],
    voicedMicroWin: ['on-beat↔light layback A/B 2쌍'],
    anatomyEntry: 'pulse 확인',
    anatomyMain: 'On-Beat / Layback Contrast',
    anatomyCooldown: '가사 말하기 1회',
    variableAxes: {'placement': ['on_beat', 'light_layback'], 'phraseLength': ['1마디', '2마디']},
    allowsToneAB: true,
  ),
  'RB-03': Card(
    id: 'RB-03',
    cue: ['세 음을 아주 느리게.', '음마다 모음을 분명하게.', '한 번에 빨라지지 않기.', '네 번 뒤 멈추기.'],
    voicedMicroWin: ['느린 3음 melisma 최대 4회'],
    anatomyEntry: '3음 패턴 듣기',
    anatomyMain: 'Slow Three-Note Melisma',
    anatomyCooldown: '가벼운 허밍',
    variableAxes: {'direction': ['상행', '하행', '왕복'], 'vowel': ['u', 'a']},
    deferredVisualFeedback: true,
    safetyIntensity: 'moderate',
    maxReps: 4,
    maxDurationSec: 120,
  ),
  'RB-04': Card(
    id: 'RB-04',
    cue: ['느린 run을 한 모음으로.', '음마다 턱을 흔들지 않기.', '가사 모음으로 한 번 전이.', '정확도가 흐려지면 느리게.'],
    voicedMicroWin: ['한 모음→가사 모음 agility 3회'],
    anatomyEntry: '모음 1회',
    anatomyMain: 'Vowel Continuity in Run',
    anatomyCooldown: '하행 허밍',
    variableAxes: {'vowel': ['u', 'a', 'e'], 'tempo': ['very_slow', 'slow']},
    safetyIntensity: 'moderate',
    maxReps: 3,
  ),
  'RB-05': Card(
    id: 'RB-05',
    cue: ['짧은 phrase를 clean으로.', 'warm으로 한 번.', '아주 짧게 airy 느낌 한 번.', '피로하면 clean만 남기기.'],
    voicedMicroWin: ['clean·warm·slightly-airy 짧은 A/B/C'],
    anatomyEntry: '편한 clean tone',
    anatomyMain: 'Controlled Tone-Color Contrast',
    anatomyCooldown: 'clean tone 허밍',
    variableAxes: {'tone': ['clean', 'warm', 'slightly_airy'], 'phraseLength': ['1마디', '2마디']},
    timbreTags: ['rnb', 'clean', 'warm', 'slightlyAiry'],
    allowsToneAB: true,
    safetyIntensity: 'moderate',
    maxTakeCount: 3,
  ),
  'RB-06': Card(
    id: 'RB-06',
    cue: ['짧은 기본 melody 한 번.', '끝 두 음만 새 contour로.', '첫 take와 비교.', '편한 ad-lib 하나만 저장.'],
    voicedMicroWin: ['기본 phrase→짧은 ad-lib contour 2쌍'],
    anatomyEntry: '기본 melody 듣기',
    anatomyMain: 'Ad-Lib Contour & Take Review',
    anatomyCooldown: '기본 melody로 복귀',
    variableAxes: {'change': ['마지막 2음', '리듬 1곳'], 'review': ['clarity', 'comfort', 'groove']},
    allowsToneAB: true,
    requiresSameRecordingCondition: true,
    maxTakeCount: 2,
  ),

  // ===== v9 Advanced Rock / Band 저위험 전용 카드 =====
  'RK-01': Card(
    id: 'RK-01',
    cue: ['clean tone으로 후렴 한 줄.', '자음과 리듬을 또렷하게.', '소리를 키우기보다 마이크를 사용.', '외치는 느낌이면 중단.'],
    voicedMicroWin: ['clean chorus line 3회'],
    anatomyEntry: '가사 말하기',
    anatomyMain: 'Clean Chorus Energy',
    anatomyCooldown: '가벼운 SOVT',
    variableAxes: {'energy': ['medium', 'moderate_plus'], 'phraseLength': ['1마디', '2마디']},
    safetyIntensity: 'moderate',
    maxReps: 3,
  ),
  'RK-02': Card(
    id: 'RK-02',
    cue: ['반주가 있는 상태에서 가사 말하기.', '핵심 자음만 짧게.', '같은 line을 clean tone으로.', '음량 경쟁은 하지 않기.'],
    voicedMicroWin: ['dense mix 위 lyric clarity 3회'],
    anatomyEntry: '반주 위 리듬 말하기',
    anatomyMain: 'Lyric Clarity in Dense Mix',
    anatomyCooldown: '무반주 말하기',
    variableAxes: {'mixDensity': ['light', 'medium'], 'consonantFocus': ['onset', 'final']},
  ),
  'RK-03': Card(
    id: 'RK-03',
    cue: ['편한 말소리로 마이크 거리 확인.', '짧은 노래 line 한 번.', 'clipping 없는 위치 표시.', '같은 위치에서 다시.'],
    voicedMicroWin: ['mic base-zone check 2쌍'],
    anatomyEntry: '말소리 거리 확인',
    anatomyMain: 'Rock Mic Base Zone',
    anatomyCooldown: '녹음 재생 확인',
    variableAxes: {'distance': ['20cm', '30cm'], 'source': ['speech', 'clean_singing']},
    allowsToneAB: true,
    requiresSameRecordingCondition: true,
  ),
  'RK-04': Card(
    id: 'RK-04',
    cue: ['phrase peak 직전 마이크 위치 확인.', 'peak에서 조금 멀리.', '목의 힘은 그대로 늘리지 않기.', '두 take만 비교.'],
    voicedMicroWin: ['peak mic pull-back A/B 2회'],
    anatomyEntry: 'peak 위치 표시',
    anatomyMain: 'Peak Pull-Back',
    anatomyCooldown: '가벼운 허밍',
    variableAxes: {'movement': ['small_pullback', 'return'], 'phraseLength': ['1마디']},
    allowsToneAB: true,
    maxTakeCount: 2,
  ),
  'RK-05': Card(
    id: 'RK-05',
    cue: ['30–45초 clean chorus 구간.', '두 take 사이 충분히 쉬기.', '두 번째 take 뒤 종료.', '거칠어지면 첫 take만 남기기.'],
    voicedMicroWin: ['짧은 chorus stamina take 최대 2회'],
    anatomyEntry: '목 상태와 key 확인',
    anatomyMain: 'Short Clean-Chorus Stamina',
    anatomyCooldown: 'SOVT와 휴식',
    variableAxes: {'duration': ['30초', '45초'], 'take': ['1', '2']},
    safetyIntensity: 'moderate',
    maxDurationSec: 45,
    maxTakeCount: 2,
    requiredRestHours: 24,
  ),
  'RK-06': Card(
    id: 'RK-06',
    cue: ['take 이름을 가리고 A/B 듣기.', '가사·박자·편안함만 표시.', '더 큰 take를 자동 선택하지 않기.', '다음 cue 하나 저장.'],
    voicedMicroWin: ['blind A/B review + 다음 cue'],
    anatomyEntry: 'A/B 순서 섞기',
    anatomyMain: 'Blind Take Review',
    anatomyCooldown: '듣기-only 정리',
    variableAxes: {'review': ['lyric', 'timing', 'comfort'], 'display': ['blind']},
    allowsToneAB: true,
  ),

  // ===== v9 Advanced CCM / Worship 저위험 전용 카드 =====
  'WC-01': Card(
    id: 'WC-01',
    cue: ['가사의 핵심 문장 하나.', '말로 자연스럽게 전달.', '같은 의도로 노래.', '감정을 음량으로만 만들지 않기.'],
    voicedMicroWin: ['text intention→singing 3회'],
    anatomyEntry: '가사 말하기',
    anatomyMain: 'Worship Text & Intention',
    anatomyCooldown: '작은 말소리 정리',
    variableAxes: {'intent': ['calm', 'hopeful', 'clear'], 'phraseLength': ['1마디', '2마디']},
    allowsToneAB: true,
  ),
  'WC-02': Card(
    id: 'WC-02',
    cue: ['긴 phrase의 숨 위치 표시.', '첫 절반을 가볍게.', '짧게 갱신하고 이어가기.', '끝에서 밀지 않기.'],
    voicedMicroWin: ['phrase economy 3회'],
    anatomyEntry: 'breath mark',
    anatomyMain: 'Long-Phrase Economy',
    anatomyCooldown: '느린 날숨',
    variableAxes: {'phraseLength': ['6박', '8박'], 'renewal': ['없음', '한 번']},
  ),
  'WC-03': Card(
    id: 'WC-03',
    cue: ['같은 후렴을 최대 두 번.', '두 번째에도 key와 톤 유지.', '피로가 늘면 바로 종료.', '반복 뒤 회복.'],
    voicedMicroWin: ['repeated chorus drift check 최대 2회'],
    anatomyEntry: '목 상태·key 확인',
    anatomyMain: 'Repeated-Chorus Drift',
    anatomyCooldown: 'SOVT 또는 듣기-only',
    variableAxes: {'repeat': ['1', '2'], 'review': ['pitch', 'tone', 'effort']},
    allowsToneAB: true,
    safetyIntensity: 'moderate',
    maxTakeCount: 2,
    requiredRestHours: 24,
  ),
  'WC-04': Card(
    id: 'WC-04',
    cue: ['밴드 반주 위 가사를 말하기.', '마이크 위치 확인.', 'clean tone으로 한 줄.', '반주보다 크게 밀지 않기.'],
    voicedMicroWin: ['band mix lyric/mic clarity 3회'],
    anatomyEntry: '반주 위 말하기',
    anatomyMain: 'Band & Mic Clarity',
    anatomyCooldown: '무반주 재생 확인',
    variableAxes: {'mix': ['light', 'medium'], 'distance': ['20cm', '30cm']},
    allowsToneAB: true,
  ),
  'WC-05': Card(
    id: 'WC-05',
    cue: ['공동 melody의 첫 음 듣기.', '정박에 clean tone으로 진입.', '장식 없이 핵심 melody 유지.', '가사 명료도 확인.'],
    voicedMicroWin: ['core melody entry 4회'],
    anatomyEntry: '첫 음과 pulse 듣기',
    anatomyMain: 'Congregational Entry & Core Melody',
    anatomyCooldown: '가사 말하기',
    variableAxes: {'entry': ['정박', 'pickup'], 'phraseLength': ['1마디', '2마디']},
    deferredVisualFeedback: true,
  ),
  'WC-06': Card(
    id: 'WC-06',
    cue: ['짧은 verse 또는 chorus 한 take.', '가사·호흡·톤을 따로 기록.', '다시 부르기 전 듣기.', 'best take 하나만 저장.'],
    voicedMicroWin: ['worship one-take review 1쌍'],
    anatomyEntry: '목표 1개 선택',
    anatomyMain: 'One-Take Review',
    anatomyCooldown: '듣기-only 자기평가',
    variableAxes: {'section': ['verse', 'chorus'], 'review': ['lyric', 'breath', 'tone']},
    allowsToneAB: true,
    requiresSameRecordingCondition: true,
    maxTakeCount: 2,
  ),

};

/// I5 — 안전 게이트 대상(safetyReview:pending) 카드 ID 집합.
/// 미사인오프(safetyApproved=false) 시 코스 manifest에서 fallback으로 대체하거나
/// fallback이 없으면 제외한다(belt/cover 등 비활성).
/// W1 — pending 카드 중 *유효 사인오프가 없는* 것의 id 집합(=여전히 잠긴 카드).
/// signoff 인자 생략 시 체크인된 [kSafetySignoff](기본 빈)을 사용 → 빈 레코드면
/// 모든 pending 카드 잠금(하위 호환). 사람이 레코드에 항목을 추가하면 그 카드만 해제.
Set<String> safetyGatedCardIds([
  Map<String, SafetySignoff> signoff = kSafetySignoff,
]) =>
    {
      for (final e in kCardLibrary.entries)
        if (e.value.safetyReview == SafetyReview.pending &&
            !(signoff[e.key]?.isValid ?? false))
          e.key,
    };

/// 잠긴 고위험 카드의 안전 대체 카드. fallback이 없으면 해당 슬롯은 숨김 처리한다.
String? safetyFallbackCardId(String id) {
  final fallback = kCardLibrary[id]?.fallbackCardId ?? '';
  return fallback.isEmpty ? null : fallback;
}

/// PathSlot → Card 해석. V1 = 라이브러리 lookup.
/// 카드 미등록 시 ArgumentError(전수 가드 테스트 C2.3가 강제).
Card resolveCard(PathSlot slot) {
  final c = kCardLibrary[slot.cardId];
  if (c == null) {
    throw ArgumentError('Card not in library: ${slot.cardId}');
  }
  return c;
}
